/*
Service Manager

Service Manager provides REST APIs that are responsible for the creation and consumption of service instances in any connected runtime environment.   Use the Service Manager APIs to perform various operations related to your platforms, service brokers, service instances, and service bindings.  Get service plans and service offerings associated with your environment.    #### Platforms   Platforms are OSBAPI-enabled software systems on which applications and services are hosted.   With the Service Manager, you can now register your platform and enable it to consume the SAP BTP services from your native environment.   This registration results in a returned set of credentials that are needed to deploy the Service Manager agent.     #### Service Brokers   Service brokers act as brokers between the Service Manager and a platform’s marketplace to advertise catalogues of service offerings and service plans.  They also receive and process the requests from the marketplace to provision, bind, unbind, and deprovision these offerings and plans.    #### Service Instances   Service instances are instantiations of service plans that make the functionality of those service plans available for consumption.    #### Service Bindings   Service bindings provide access details to existing service instances.  The access details are part of the service bindings' ‘credentials’ property, and typically include access URLs and credentials.    #### Service Plans   Service plans represent sets of capabilities provided by a service offering.  For example, database service offerings provide different plans for different database versions or sizes, while the Service Manager plans offer different data access levels.    #### Service Offerings   Service offerings are advertisements of the services that are supported by a service broker.  For example, software that you can consume in the subaccount.  Service offerings are related to one or more service plans.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// OperationResponseObjectErrors struct for OperationResponseObjectErrors
type OperationResponseObjectErrors struct {
	Error *Error
	ArrayOfError *[]Error
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *OperationResponseObjectErrors) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Error
	err = json.Unmarshal(data, &dst.Error);
	if err == nil {
		jsonError, _ := json.Marshal(dst.Error)
		if string(jsonError) == "{}" { // empty struct
			dst.Error = nil
		} else {
			return nil // data stored in dst.Error, return on the first match
		}
	} else {
		dst.Error = nil
	}

	// try to unmarshal JSON data into ArrayOfError
	err = json.Unmarshal(data, &dst.ArrayOfError);
	if err == nil {
		jsonArrayOfError, _ := json.Marshal(dst.ArrayOfError)
		if string(jsonArrayOfError) == "{}" { // empty struct
			dst.ArrayOfError = nil
		} else {
			return nil // data stored in dst.ArrayOfError, return on the first match
		}
	} else {
		dst.ArrayOfError = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(OperationResponseObjectErrors)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *OperationResponseObjectErrors) MarshalJSON() ([]byte, error) {
	if src.Error != nil {
		return json.Marshal(&src.Error)
	}

	if src.ArrayOfError != nil {
		return json.Marshal(&src.ArrayOfError)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableOperationResponseObjectErrors struct {
	value *OperationResponseObjectErrors
	isSet bool
}

func (v NullableOperationResponseObjectErrors) Get() *OperationResponseObjectErrors {
	return v.value
}

func (v *NullableOperationResponseObjectErrors) Set(val *OperationResponseObjectErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationResponseObjectErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationResponseObjectErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationResponseObjectErrors(val *OperationResponseObjectErrors) *NullableOperationResponseObjectErrors {
	return &NullableOperationResponseObjectErrors{value: val, isSet: true}
}

func (v NullableOperationResponseObjectErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationResponseObjectErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


