---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: filters.example.crossplane.io
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XBTPResources
  mode: Pipeline
  pipeline:
    - step: create-resources
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: account.btp.sap.crossplane.io/v1alpha1
            kind: ServiceInstance
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: prod-instance
            spec:
              forProvider:
                name: prod-instance
            ---
            apiVersion: account.btp.sap.crossplane.io/v1alpha1
            kind: ServiceInstance
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: dev-instance
            spec:
              forProvider:
                name: dev-instance
            ---
            apiVersion: account.btp.sap.crossplane.io/v1alpha1
            kind: ServiceInstance
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: test-skip-instance
            spec:
              forProvider:
                name: test-skip-instance
    - step: import-btp
      functionRef:
        name: function-btp-importer
      input:
        apiVersion: import.btp.sap.crossplane.io/v1beta1
        kind: Input
        mode: auto
        include:
          - "prod-.*" # only attempt import for resources whose name starts with "prod-"
        exclude:
          - ".*-skip$" # skip resources whose name ends with "-skip"
        secretRef:
          name:
            value: "my-namespace-btp-provider-config"
          namespace:
            value: "my-namespace"
          key: "cisCredentials"
