providerConfigRefName: default-canary
managementPolicy: Observe
resources:
    - type: Subaccount
      name: dcom-demo
      managementPolicy: Observe
      filters: {}
tooling:
    - subaccount: dcom-demo
      kind: Entitlement
      secretReference:
        name: dcom-demo-cis-entitlement
        namespace: default
    - subaccount: dcom-demo
      kind: ServiceManager
      secretReference:
        name: dcom-demo-sm-binding
        namespace: default
    - subaccount: dcom-demo
      kind: CloudManagement
      secretReference:
        name: dcom-demo-cis-binding
        namespace: default
