/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type CertificatesOnSubaccountLevelAPI interface {

	/*
	V1SubaccountCertificatesCertificateNameDelete Delete a certificate posted on subaccount level

	Delete a certificate posted on subaccount level. Subaccount is determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Subaccount id
	@return ApiV1SubaccountCertificatesCertificateNameDeleteRequest
	*/
	V1SubaccountCertificatesCertificateNameDelete(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameDeleteRequest

	// V1SubaccountCertificatesCertificateNameDeleteExecute executes the request
	//  @return Update
	V1SubaccountCertificatesCertificateNameDeleteExecute(r ApiV1SubaccountCertificatesCertificateNameDeleteRequest) (*Update, *http.Response, error)

	/*
	V1SubaccountCertificatesCertificateNameGet Get a certificate posted on subaccount level

	Get a certificate (base64 encoded string, as a JSON object) posted on subaccount level. Subaccount is determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName subaccount id
	@return ApiV1SubaccountCertificatesCertificateNameGetRequest
	*/
	V1SubaccountCertificatesCertificateNameGet(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameGetRequest

	// V1SubaccountCertificatesCertificateNameGetExecute executes the request
	//  @return Certificate
	V1SubaccountCertificatesCertificateNameGetExecute(r ApiV1SubaccountCertificatesCertificateNameGetRequest) (*Certificate, *http.Response, error)

	/*
	V1SubaccountCertificatesCertificateNameLabelsGet Get all labels for a certificate posted on subaccount level

	Get a list of labels (as a JSON array) assigned to a certificate posted on subaccount level. 
If none are found, an empty array is returned. 
Subaccount is determined by the passed OAuth access token in the Authorization header.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest
	*/
	V1SubaccountCertificatesCertificateNameLabelsGet(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest

	// V1SubaccountCertificatesCertificateNameLabelsGetExecute executes the request
	//  @return []Label
	V1SubaccountCertificatesCertificateNameLabelsGetExecute(r ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest) ([]Label, *http.Response, error)

	/*
	V1SubaccountCertificatesCertificateNameLabelsPatch Add or remove labels for a certificate posted on subaccount level

	Add or remove labels assigned to a certificate posted on subaccount level. 
Subaccount is determined by the passed OAuth access token in the Authorization header.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest
	*/
	V1SubaccountCertificatesCertificateNameLabelsPatch(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest

	// V1SubaccountCertificatesCertificateNameLabelsPatchExecute executes the request
	V1SubaccountCertificatesCertificateNameLabelsPatchExecute(r ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest) (*http.Response, error)

	/*
	V1SubaccountCertificatesCertificateNameLabelsPut Replace all labels for a certificate posted on subaccount level

	Replace all labels assigned to a certificate posted on subaccount level with the labels specified in the request body. 
Subaccount is determined by the passed OAuth access token in the Authorization header.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest
	*/
	V1SubaccountCertificatesCertificateNameLabelsPut(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest

	// V1SubaccountCertificatesCertificateNameLabelsPutExecute executes the request
	V1SubaccountCertificatesCertificateNameLabelsPutExecute(r ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest) (*http.Response, error)

	/*
	V1SubaccountCertificatesCertificateNamePublicKeysGet Get the public part of a specified certificate

	Get a certificate chain in PEM format (Base64 encoded string, as a JSON object) of a specified certificate. In case of a keystore, the response will contain certificate chain for each alias. The public part of password-protected keystores can be retrieved only for PEM certificates and certificates generated using attributes. Subaccount is determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name on subaccount level
	@return ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest
	*/
	V1SubaccountCertificatesCertificateNamePublicKeysGet(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest

	// V1SubaccountCertificatesCertificateNamePublicKeysGetExecute executes the request
	//  @return []PublicKey
	V1SubaccountCertificatesCertificateNamePublicKeysGetExecute(r ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest) ([]PublicKey, *http.Response, error)

	/*
	V1SubaccountCertificatesDelete Delete certificates posted on subaccount level

	Delete certificates posted on subaccount level. Subaccount is
determined by the passed OAuth access token.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1SubaccountCertificatesDeleteRequest
	*/
	V1SubaccountCertificatesDelete(ctx context.Context) ApiV1SubaccountCertificatesDeleteRequest

	// V1SubaccountCertificatesDeleteExecute executes the request
	//  @return string
	V1SubaccountCertificatesDeleteExecute(r ApiV1SubaccountCertificatesDeleteRequest) (string, *http.Response, error)

	/*
	V1SubaccountCertificatesGet Get all certificates posted on subaccount level

	Get all certificates (as a JSON array) posted on subaccount level.
In none is found, an empty array is returned. Subaccount is determined by
the passed OAuth access token.

For requests which return a large number of certificates, chunked handling of the response will be enabled. If an error occurs with the request processing while chunking is enabled, no response will be returned to the client.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1SubaccountCertificatesGetRequest
	*/
	V1SubaccountCertificatesGet(ctx context.Context) ApiV1SubaccountCertificatesGetRequest

	// V1SubaccountCertificatesGetExecute executes the request
	//  @return []V1SubaccountCertificatesGet200ResponseInner
	V1SubaccountCertificatesGetExecute(r ApiV1SubaccountCertificatesGetRequest) ([]V1SubaccountCertificatesGet200ResponseInner, *http.Response, error)

	/*
	V1SubaccountCertificatesPost Post a new certificate or new certificates on subaccount level

	Post a new certificate (base64 encoded string, as a JSON object) or new certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on subaccount level. Subaccount is determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1SubaccountCertificatesPostRequest
	*/
	V1SubaccountCertificatesPost(ctx context.Context) ApiV1SubaccountCertificatesPostRequest

	// V1SubaccountCertificatesPostExecute executes the request
	//  @return []BulkResponse
	V1SubaccountCertificatesPostExecute(r ApiV1SubaccountCertificatesPostRequest) ([]BulkResponse, *http.Response, error)

	/*
	V1SubaccountCertificatesPut Update a certificate or certificates on subaccount level

	Update a certificate (base64 encoded string, as a JSON object) or certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on subaccount level. Subaccount is determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1SubaccountCertificatesPutRequest
	*/
	V1SubaccountCertificatesPut(ctx context.Context) ApiV1SubaccountCertificatesPutRequest

	// V1SubaccountCertificatesPutExecute executes the request
	//  @return V1SubaccountDestinationsPut200Response
	V1SubaccountCertificatesPutExecute(r ApiV1SubaccountCertificatesPutRequest) (*V1SubaccountDestinationsPut200Response, *http.Response, error)
}

// CertificatesOnSubaccountLevelAPIService CertificatesOnSubaccountLevelAPI service
type CertificatesOnSubaccountLevelAPIService service

type ApiV1SubaccountCertificatesCertificateNameDeleteRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificateName string
}

func (r ApiV1SubaccountCertificatesCertificateNameDeleteRequest) Execute() (*Update, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesCertificateNameDeleteExecute(r)
}

/*
V1SubaccountCertificatesCertificateNameDelete Delete a certificate posted on subaccount level

Delete a certificate posted on subaccount level. Subaccount is determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Subaccount id
 @return ApiV1SubaccountCertificatesCertificateNameDeleteRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameDelete(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameDeleteRequest {
	return ApiV1SubaccountCertificatesCertificateNameDeleteRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return Update
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameDeleteExecute(r ApiV1SubaccountCertificatesCertificateNameDeleteRequest) (*Update, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Update
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesCertificateNameDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates/{certificate name}"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesCertificateNameGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificateName string
	ifNoneMatch *string
	ifMatch *string
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value is different from the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 304 (Not Modified) and empty response body. If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1SubaccountCertificatesCertificateNameGetRequest) IfNoneMatch(ifNoneMatch string) ApiV1SubaccountCertificatesCertificateNameGetRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value matches the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 412 (Precondition Failed). If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1SubaccountCertificatesCertificateNameGetRequest) IfMatch(ifMatch string) ApiV1SubaccountCertificatesCertificateNameGetRequest {
	r.ifMatch = &ifMatch
	return r
}

func (r ApiV1SubaccountCertificatesCertificateNameGetRequest) Execute() (*Certificate, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesCertificateNameGetExecute(r)
}

/*
V1SubaccountCertificatesCertificateNameGet Get a certificate posted on subaccount level

Get a certificate (base64 encoded string, as a JSON object) posted on subaccount level. Subaccount is determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName subaccount id
 @return ApiV1SubaccountCertificatesCertificateNameGetRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameGet(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameGetRequest {
	return ApiV1SubaccountCertificatesCertificateNameGetRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return Certificate
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameGetExecute(r ApiV1SubaccountCertificatesCertificateNameGetRequest) (*Certificate, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Certificate
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesCertificateNameGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates/{certificate name}"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ifNoneMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "simple", "")
	}
	if r.ifMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificateName string
}

func (r ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest) Execute() ([]Label, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesCertificateNameLabelsGetExecute(r)
}

/*
V1SubaccountCertificatesCertificateNameLabelsGet Get all labels for a certificate posted on subaccount level

Get a list of labels (as a JSON array) assigned to a certificate posted on subaccount level. 
If none are found, an empty array is returned. 
Subaccount is determined by the passed OAuth access token in the Authorization header.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameLabelsGet(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest {
	return ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return []Label
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameLabelsGetExecute(r ApiV1SubaccountCertificatesCertificateNameLabelsGetRequest) ([]Label, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Label
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesCertificateNameLabelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates/{certificate name}/labels"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v V1SubaccountDestinationsPut400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificateName string
	patchLabels *PatchLabels
}

// A JSON object describing the action performed and an array of labels (as JSON objects) to be assigned to or removed from the certificate. The value of the action property must be either &#x60;ADD&#x60; or &#x60;DELETE&#x60;. Each label JSON object must contain a &#x60;key&#x60; property and a &#x60;values&#x60; property.
func (r ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest) PatchLabels(patchLabels PatchLabels) ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest {
	r.patchLabels = &patchLabels
	return r
}

func (r ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesCertificateNameLabelsPatchExecute(r)
}

/*
V1SubaccountCertificatesCertificateNameLabelsPatch Add or remove labels for a certificate posted on subaccount level

Add or remove labels assigned to a certificate posted on subaccount level. 
Subaccount is determined by the passed OAuth access token in the Authorization header.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameLabelsPatch(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest {
	return ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameLabelsPatchExecute(r ApiV1SubaccountCertificatesCertificateNameLabelsPatchRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesCertificateNameLabelsPatch")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates/{certificate name}/labels"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.patchLabels == nil {
		return nil, reportError("patchLabels is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.patchLabels
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v V1SubaccountDestinationsPut400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificateName string
	label *[]Label
}

// An array of labels (as JSON objects) to be assigned to the certificate. Each label JSON object must contain a &#x60;key&#x60; property and a &#x60;values&#x60; property.
func (r ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest) Label(label []Label) ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest {
	r.label = &label
	return r
}

func (r ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesCertificateNameLabelsPutExecute(r)
}

/*
V1SubaccountCertificatesCertificateNameLabelsPut Replace all labels for a certificate posted on subaccount level

Replace all labels assigned to a certificate posted on subaccount level with the labels specified in the request body. 
Subaccount is determined by the passed OAuth access token in the Authorization header.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameLabelsPut(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest {
	return ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNameLabelsPutExecute(r ApiV1SubaccountCertificatesCertificateNameLabelsPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesCertificateNameLabelsPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates/{certificate name}/labels"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.label == nil {
		return nil, reportError("label is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.label
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v V1SubaccountDestinationsPut400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificateName string
	ifNoneMatch *string
	ifMatch *string
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value is different from the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 304 (Not Modified) and empty response body. If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest) IfNoneMatch(ifNoneMatch string) ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value matches the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 412 (Precondition Failed). If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest) IfMatch(ifMatch string) ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest {
	r.ifMatch = &ifMatch
	return r
}

func (r ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest) Execute() ([]PublicKey, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesCertificateNamePublicKeysGetExecute(r)
}

/*
V1SubaccountCertificatesCertificateNamePublicKeysGet Get the public part of a specified certificate

Get a certificate chain in PEM format (Base64 encoded string, as a JSON object) of a specified certificate. In case of a keystore, the response will contain certificate chain for each alias. The public part of password-protected keystores can be retrieved only for PEM certificates and certificates generated using attributes. Subaccount is determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name on subaccount level
 @return ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNamePublicKeysGet(ctx context.Context, certificateName string) ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest {
	return ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return []PublicKey
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesCertificateNamePublicKeysGetExecute(r ApiV1SubaccountCertificatesCertificateNamePublicKeysGetRequest) ([]PublicKey, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []PublicKey
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesCertificateNamePublicKeysGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates/{certificate name}/publicKeys"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ifNoneMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "simple", "")
	}
	if r.ifMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesDeleteRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	filter *string
}

// A filter expression, which specifies what certificates to delete. It can only be an in-list condition.  ## In-list condition  Syntax: &#x60;$filter&#x3D;Name in (&lt;list_of_names&gt;)&#x60;  Deletes all certificates with the specified names from the list. Every name in the list of names should be [percent-encoded](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1) and after that surrounded by single quotes.  For example, let&#39;s look at two certificates with names \&quot;our team&#39;s app.pem\&quot; and \&quot;workflow (new).pem\&quot;.  The query parameter for them would be constructed as follows:  &#x60;&#x60;&#x60; $filter&#x3D;Name in (&#39;our%20team%27s%20app.pem&#39;, &#39;workflow%20%28new%29.pem&#39;) &#x60;&#x60;&#x60;  You can pass this value to curl&#39;s **--data-urlencode** option and the resulting URI for the HTTP request would end like this:  &#x60;&#x60;&#x60; /destination-configuration/v1/subaccountCertificates?$filter&#x3D;Name+in+%28%27our%2520team%2527s%2520app.pem%27%2c+%27workflow%2520%2528new%2529.pem%27%29 &#x60;&#x60;&#x60;  Note: &#x60;Name&#x60; is the only supported field. 
func (r ApiV1SubaccountCertificatesDeleteRequest) Filter(filter string) ApiV1SubaccountCertificatesDeleteRequest {
	r.filter = &filter
	return r
}

func (r ApiV1SubaccountCertificatesDeleteRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesDeleteExecute(r)
}

/*
V1SubaccountCertificatesDelete Delete certificates posted on subaccount level

Delete certificates posted on subaccount level. Subaccount is
determined by the passed OAuth access token.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1SubaccountCertificatesDeleteRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesDelete(ctx context.Context) ApiV1SubaccountCertificatesDeleteRequest {
	return ApiV1SubaccountCertificatesDeleteRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return string
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesDeleteExecute(r ApiV1SubaccountCertificatesDeleteRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.filter == nil {
		return localVarReturnValue, nil, reportError("filter is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "$filter", r.filter, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	filter *string
	includeMetadata *string
	select_ *string
	page *int32
	pageSize *int32
	pageCount *bool
	entityCount *bool
}

// A filter expression, which specifies what certificates to return. It can only be an in-list condition.  Allowed only in the default mode. As such, **$filter** cannot be combined with **$select**, nor **$page**.  ## In-list condition  Syntax: &#x60;$filter&#x3D;Name in (&lt;list_of_names&gt;)&#x60;  Retrieves all certificates with the specified names from the list. Every name in the list of names should be [percent-encoded](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1) and after that surrounded by single quotes.  For example, let&#39;s look at two certificates with names \&quot;our-team&#39;s-app.pem\&quot; and \&quot;SAP_John&#39;s_certificate\&quot;.  The query parameter for them would be constructed as follows:  &#x60;&#x60;&#x60; $filter&#x3D;Name in (&#39;our-team%27s-app.pem&#39;, &#39;SAP_John%27s_certificate&#39;) &#x60;&#x60;&#x60;  You can pass this value to curl&#39;s **--data-urlencode** option and the resulting URI for the HTTP request would end like this:  &#x60;&#x60;&#x60; /destination-configuration/v1/subaccountCertificates?$filter&#x3D;Name+in+%28%27our-team%2527s-app.pem%27%2C+%27SAP_John%2527s_certificate%27%29 &#x60;&#x60;&#x60;  Note: &#x60;Name&#x60; is the only supported field.  ## Has Label condition  Syntax: &#x60;$filter&#x3D;Label[&#39;&lt;label-key&gt;&#39;] HAS (&#39;&lt;label-value-1&gt;&#39;, &#39;&lt;label-value-2&gt;&#39;)&#x60;  Retrieves all certificates that have been assigned labels which contain all of the requested label values.  For example, to get all certificates that have been assigned a label &#39;token-type&#39; with values &#39;xsuaa&#39; and &#39;ias&#39;, the filter would be:  &#x60;&#x60;&#x60; $filter&#x3D;Label[&#39;token-type&#39;] HAS (&#39;xsuaa&#39;, &#39;ias&#39;) &#x60;&#x60;&#x60; 
func (r ApiV1SubaccountCertificatesGetRequest) Filter(filter string) ApiV1SubaccountCertificatesGetRequest {
	r.filter = &filter
	return r
}

// Include metadata in the response. Each configuration will contain an additional property **$metadata** with the value of an object, containing the names of the requested metadata properties as keys, and their values.  Allowed only in the default mode. As such, **$includeMetadata** cannot be combined with **$select**, nor **$page**.  Syntax: &#x60;&#x60;&#x60; $includeMetadata&#x3D;&lt;metadata1&gt;;&lt;metadata2&gt;;... &#x60;&#x60;&#x60;  Note: Currently only &#x60;modification_time&#x60;, &#x60;etag&#x60;, &#x60;shared_with_subscriber&#x60; and &#x60;labels&#x60; are metadata that can be included. 
func (r ApiV1SubaccountCertificatesGetRequest) IncludeMetadata(includeMetadata string) ApiV1SubaccountCertificatesGetRequest {
	r.includeMetadata = &includeMetadata
	return r
}

// Enable select mode, in order to retrieve only certificate names.   In select mode the response changes from a list of certificates to a list of their names. Only the &#x60;Name&#x60; field is supported as a value.  Note: Only one mode is allowed for a request. As such, **$select** cannot be combined with **$page**, nor **$filter**. 
func (r ApiV1SubaccountCertificatesGetRequest) Select_(select_ string) ApiV1SubaccountCertificatesGetRequest {
	r.select_ = &select_
	return r
}

// Enable pagination mode and retrieve the specified page number.  In pagination mode the list of certificates is partitioned into pages of size **$pageSize** and only the specified page is returned. Page numbering starts from 1.  Note: Only one mode is allowed for a request. As such, **$page** cannot be combined with **$select**, nor **$filter**. 
func (r ApiV1SubaccountCertificatesGetRequest) Page(page int32) ApiV1SubaccountCertificatesGetRequest {
	r.page = &page
	return r
}

// Number of items in each page.  Allowed only in pagination mode (see **$page** query parameter). 
func (r ApiV1SubaccountCertificatesGetRequest) PageSize(pageSize int32) ApiV1SubaccountCertificatesGetRequest {
	r.pageSize = &pageSize
	return r
}

// Whether to return the information about the total count of pages for the request, via **Page-Count** response header.  Allowed only in pagination mode (see **$page** query parameter). 
func (r ApiV1SubaccountCertificatesGetRequest) PageCount(pageCount bool) ApiV1SubaccountCertificatesGetRequest {
	r.pageCount = &pageCount
	return r
}

// Whether to return the information about the total count of entities for the request, via **Entity-Count** response header.  Allowed only in pagination mode (see **$page** query parameter). 
func (r ApiV1SubaccountCertificatesGetRequest) EntityCount(entityCount bool) ApiV1SubaccountCertificatesGetRequest {
	r.entityCount = &entityCount
	return r
}

func (r ApiV1SubaccountCertificatesGetRequest) Execute() ([]V1SubaccountCertificatesGet200ResponseInner, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesGetExecute(r)
}

/*
V1SubaccountCertificatesGet Get all certificates posted on subaccount level

Get all certificates (as a JSON array) posted on subaccount level.
In none is found, an empty array is returned. Subaccount is determined by
the passed OAuth access token.

For requests which return a large number of certificates, chunked handling of the response will be enabled. If an error occurs with the request processing while chunking is enabled, no response will be returned to the client.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1SubaccountCertificatesGetRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesGet(ctx context.Context) ApiV1SubaccountCertificatesGetRequest {
	return ApiV1SubaccountCertificatesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []V1SubaccountCertificatesGet200ResponseInner
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesGetExecute(r ApiV1SubaccountCertificatesGetRequest) ([]V1SubaccountCertificatesGet200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []V1SubaccountCertificatesGet200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$filter", r.filter, "form", "")
	}
	if r.includeMetadata != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$includeMetadata", r.includeMetadata, "form", "")
	}
	if r.select_ != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$select", r.select_, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$page", r.page, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageSize", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 10
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageSize", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.pageCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageCount", r.pageCount, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageCount", defaultValue, "form", "")
		r.pageCount = &defaultValue
	}
	if r.entityCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$entityCount", r.entityCount, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "$entityCount", defaultValue, "form", "")
		r.entityCount = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesPostRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificate *V1SubaccountCertificatesPutRequest
	includeMetadata *string
}

// The certificate (base64 encoded string, as a JSON object) / Certificates (base64 encoded string, as a JSON array) / Certificate attributes / Certificate attributes with CSR (base64 encoded PEM)
func (r ApiV1SubaccountCertificatesPostRequest) Certificate(certificate V1SubaccountCertificatesPutRequest) ApiV1SubaccountCertificatesPostRequest {
	r.certificate = &certificate
	return r
}

// Include metadata in the response.  If configurations were successfully created, the metadata for the newly created configurations is returned.  If the configurations were not created due to conflict (configuration already exists), the metadata for the existing configurations is returned.  In case a single configuration is posted, the response body will be a JSON object with property **$metadata** containing an object with the names of the requested metadata properties as keys, and their values.  In case multiple configurations are posted, each of the results in the bulk operation response will contain an additional property **$metadata** with the value of an object, containing the names of the requested metadata properties as keys, and their values.  Syntax: &#x60;&#x60;&#x60; $includeMetadata&#x3D;&lt;metadata1&gt;;&lt;metadata2&gt;;... &#x60;&#x60;&#x60;  Note: Currently only &#x60;modification_time&#x60;, &#x60;etag&#x60;, and &#x60;shared_with_subscriber&#x60; are metadata that can be included. 
func (r ApiV1SubaccountCertificatesPostRequest) IncludeMetadata(includeMetadata string) ApiV1SubaccountCertificatesPostRequest {
	r.includeMetadata = &includeMetadata
	return r
}

func (r ApiV1SubaccountCertificatesPostRequest) Execute() ([]BulkResponse, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesPostExecute(r)
}

/*
V1SubaccountCertificatesPost Post a new certificate or new certificates on subaccount level

Post a new certificate (base64 encoded string, as a JSON object) or new certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on subaccount level. Subaccount is determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1SubaccountCertificatesPostRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesPost(ctx context.Context) ApiV1SubaccountCertificatesPostRequest {
	return ApiV1SubaccountCertificatesPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []BulkResponse
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesPostExecute(r ApiV1SubaccountCertificatesPostRequest) ([]BulkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []BulkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.certificate == nil {
		return localVarReturnValue, nil, reportError("certificate is required and must be specified")
	}

	if r.includeMetadata != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$includeMetadata", r.includeMetadata, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.certificate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1SubaccountCertificatesPutRequest struct {
	ctx context.Context
	ApiService CertificatesOnSubaccountLevelAPI
	certificate *V1SubaccountCertificatesPutRequest
}

// The certificate (base64 encoded string, as a JSON object) / Certificates (base64 encoded string, as a JSON array) / Certificate attributes / Certificate attributes with CSR (base64 encoded PEM)
func (r ApiV1SubaccountCertificatesPutRequest) Certificate(certificate V1SubaccountCertificatesPutRequest) ApiV1SubaccountCertificatesPutRequest {
	r.certificate = &certificate
	return r
}

func (r ApiV1SubaccountCertificatesPutRequest) Execute() (*V1SubaccountDestinationsPut200Response, *http.Response, error) {
	return r.ApiService.V1SubaccountCertificatesPutExecute(r)
}

/*
V1SubaccountCertificatesPut Update a certificate or certificates on subaccount level

Update a certificate (base64 encoded string, as a JSON object) or certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on subaccount level. Subaccount is determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1SubaccountCertificatesPutRequest
*/
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesPut(ctx context.Context) ApiV1SubaccountCertificatesPutRequest {
	return ApiV1SubaccountCertificatesPutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return V1SubaccountDestinationsPut200Response
func (a *CertificatesOnSubaccountLevelAPIService) V1SubaccountCertificatesPutExecute(r ApiV1SubaccountCertificatesPutRequest) (*V1SubaccountDestinationsPut200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *V1SubaccountDestinationsPut200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnSubaccountLevelAPIService.V1SubaccountCertificatesPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/subaccountCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.certificate == nil {
		return localVarReturnValue, nil, reportError("certificate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.certificate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
