/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type CertificatesOnServiceInstanceSubscriptionLevelAPI interface {

	/*
	V1InstanceCertificatesCertificateNameDelete Deletes a certificate posted on service instance / subscription level

	Deletes a certificate posted on service instance / subscription level. Service instance and subaccount are determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1InstanceCertificatesCertificateNameDeleteRequest
	*/
	V1InstanceCertificatesCertificateNameDelete(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameDeleteRequest

	// V1InstanceCertificatesCertificateNameDeleteExecute executes the request
	//  @return Update
	V1InstanceCertificatesCertificateNameDeleteExecute(r ApiV1InstanceCertificatesCertificateNameDeleteRequest) (*Update, *http.Response, error)

	/*
	V1InstanceCertificatesCertificateNameGet Get a certificate posted on service instance / subscription level

	Get a certificate (base64 encoded string, as a JSON object) posted on service instance / subscription level. Service instance and subaccount are determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1InstanceCertificatesCertificateNameGetRequest
	*/
	V1InstanceCertificatesCertificateNameGet(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameGetRequest

	// V1InstanceCertificatesCertificateNameGetExecute executes the request
	//  @return Certificate
	V1InstanceCertificatesCertificateNameGetExecute(r ApiV1InstanceCertificatesCertificateNameGetRequest) (*Certificate, *http.Response, error)

	/*
	V1InstanceCertificatesCertificateNameLabelsGet Get all labels for a certificate posted on service instance / subscription level

	Get a list of labels (as a JSON array) assigned to a certificate posted on service instance / subscription level. 
If none are found, an empty array is returned. 
Service instance and subaccount are determined by the passed OAuth access token in the Authorization header.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1InstanceCertificatesCertificateNameLabelsGetRequest
	*/
	V1InstanceCertificatesCertificateNameLabelsGet(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameLabelsGetRequest

	// V1InstanceCertificatesCertificateNameLabelsGetExecute executes the request
	//  @return []Label
	V1InstanceCertificatesCertificateNameLabelsGetExecute(r ApiV1InstanceCertificatesCertificateNameLabelsGetRequest) ([]Label, *http.Response, error)

	/*
	V1InstanceCertificatesCertificateNameLabelsPatch Add or remove labels for a certificate posted on service instance / subscription level

	Add or remove labels assigned to a certificate posted on service instance / subscription level. 
Service instance and subaccount are determined by the passed OAuth access token in the Authorization header.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest
	*/
	V1InstanceCertificatesCertificateNameLabelsPatch(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest

	// V1InstanceCertificatesCertificateNameLabelsPatchExecute executes the request
	V1InstanceCertificatesCertificateNameLabelsPatchExecute(r ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest) (*http.Response, error)

	/*
	V1InstanceCertificatesCertificateNameLabelsPut Replace all labels for a certificate posted on service instance / subscription level

	Replace all labels assigned to a certificate posted on service instance / subscription level with the labels specified in the request body. 
Service instance and subaccount are determined by the passed OAuth access token in the Authorization header.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name
	@return ApiV1InstanceCertificatesCertificateNameLabelsPutRequest
	*/
	V1InstanceCertificatesCertificateNameLabelsPut(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameLabelsPutRequest

	// V1InstanceCertificatesCertificateNameLabelsPutExecute executes the request
	V1InstanceCertificatesCertificateNameLabelsPutExecute(r ApiV1InstanceCertificatesCertificateNameLabelsPutRequest) (*http.Response, error)

	/*
	V1InstanceCertificatesCertificateNamePublicKeysGet Get the public part of a specified certificate

	Get a certificate chain in PEM format (Base64 encoded string, as a JSON object) of a specified certificate. In case of a keystore, the response will contain certificate chain for each alias. The public part of password-protected keystores can be retrieved only for PEM certificates and certificates generated using attributes. Service instance and subaccount are determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param certificateName Certificate name on instance level
	@return ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest
	*/
	V1InstanceCertificatesCertificateNamePublicKeysGet(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest

	// V1InstanceCertificatesCertificateNamePublicKeysGetExecute executes the request
	//  @return []PublicKey
	V1InstanceCertificatesCertificateNamePublicKeysGetExecute(r ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest) ([]PublicKey, *http.Response, error)

	/*
	V1InstanceCertificatesDelete Deletes certificates posted on service instance / subscription level

	Deletes certificates posted on service instance / subscription level. Service
instance and subaccount are determined by the passed OAuth access token.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1InstanceCertificatesDeleteRequest
	*/
	V1InstanceCertificatesDelete(ctx context.Context) ApiV1InstanceCertificatesDeleteRequest

	// V1InstanceCertificatesDeleteExecute executes the request
	//  @return string
	V1InstanceCertificatesDeleteExecute(r ApiV1InstanceCertificatesDeleteRequest) (string, *http.Response, error)

	/*
	V1InstanceCertificatesGet Get all certificates posted on service instance / subscription level

	Get all certificates (as a JSON array) posted on service instance
level. If none is found, an empty list is returned. Service instance and subaccount
are determined by the passed OAuth access token.

For requests which return a large number of certificates, chunked handling of the response will be enabled. If an error occurs with the request processing while chunking is enabled, no response will be returned to the client.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1InstanceCertificatesGetRequest
	*/
	V1InstanceCertificatesGet(ctx context.Context) ApiV1InstanceCertificatesGetRequest

	// V1InstanceCertificatesGetExecute executes the request
	//  @return []V1SubaccountCertificatesGet200ResponseInner
	V1InstanceCertificatesGetExecute(r ApiV1InstanceCertificatesGetRequest) ([]V1SubaccountCertificatesGet200ResponseInner, *http.Response, error)

	/*
	V1InstanceCertificatesPost Post a new certificate or certificates on service instance / subscription level

	Post a new certificate (base64 encoded string, as a JSON object) or new certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on service instance / subscription level. Service instance and subaccount are determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1InstanceCertificatesPostRequest
	*/
	V1InstanceCertificatesPost(ctx context.Context) ApiV1InstanceCertificatesPostRequest

	// V1InstanceCertificatesPostExecute executes the request
	//  @return []BulkResponse
	V1InstanceCertificatesPostExecute(r ApiV1InstanceCertificatesPostRequest) ([]BulkResponse, *http.Response, error)

	/*
	V1InstanceCertificatesPut Update a certificate or certificates on service instance / subscription level

	Update a certificate (base64 encoded string, as a JSON object) or certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on service instance / subscription level. Service instance and subaccount is determined by the passed OAuth access token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1InstanceCertificatesPutRequest
	*/
	V1InstanceCertificatesPut(ctx context.Context) ApiV1InstanceCertificatesPutRequest

	// V1InstanceCertificatesPutExecute executes the request
	//  @return V1SubaccountDestinationsPut200Response
	V1InstanceCertificatesPutExecute(r ApiV1InstanceCertificatesPutRequest) (*V1SubaccountDestinationsPut200Response, *http.Response, error)
}

// CertificatesOnServiceInstanceSubscriptionLevelAPIService CertificatesOnServiceInstanceSubscriptionLevelAPI service
type CertificatesOnServiceInstanceSubscriptionLevelAPIService service

type ApiV1InstanceCertificatesCertificateNameDeleteRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificateName string
}

func (r ApiV1InstanceCertificatesCertificateNameDeleteRequest) Execute() (*Update, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesCertificateNameDeleteExecute(r)
}

/*
V1InstanceCertificatesCertificateNameDelete Deletes a certificate posted on service instance / subscription level

Deletes a certificate posted on service instance / subscription level. Service instance and subaccount are determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1InstanceCertificatesCertificateNameDeleteRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameDelete(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameDeleteRequest {
	return ApiV1InstanceCertificatesCertificateNameDeleteRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return Update
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameDeleteExecute(r ApiV1InstanceCertificatesCertificateNameDeleteRequest) (*Update, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Update
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesCertificateNameDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates/{certificate name}"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesCertificateNameGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificateName string
	ifNoneMatch *string
	ifMatch *string
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value is different from the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 304 (Not Modified) and empty response body. If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1InstanceCertificatesCertificateNameGetRequest) IfNoneMatch(ifNoneMatch string) ApiV1InstanceCertificatesCertificateNameGetRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value matches the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 412 (Precondition Failed). If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1InstanceCertificatesCertificateNameGetRequest) IfMatch(ifMatch string) ApiV1InstanceCertificatesCertificateNameGetRequest {
	r.ifMatch = &ifMatch
	return r
}

func (r ApiV1InstanceCertificatesCertificateNameGetRequest) Execute() (*Certificate, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesCertificateNameGetExecute(r)
}

/*
V1InstanceCertificatesCertificateNameGet Get a certificate posted on service instance / subscription level

Get a certificate (base64 encoded string, as a JSON object) posted on service instance / subscription level. Service instance and subaccount are determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1InstanceCertificatesCertificateNameGetRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameGet(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameGetRequest {
	return ApiV1InstanceCertificatesCertificateNameGetRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return Certificate
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameGetExecute(r ApiV1InstanceCertificatesCertificateNameGetRequest) (*Certificate, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Certificate
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesCertificateNameGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates/{certificate name}"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ifNoneMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "simple", "")
	}
	if r.ifMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesCertificateNameLabelsGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificateName string
}

func (r ApiV1InstanceCertificatesCertificateNameLabelsGetRequest) Execute() ([]Label, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesCertificateNameLabelsGetExecute(r)
}

/*
V1InstanceCertificatesCertificateNameLabelsGet Get all labels for a certificate posted on service instance / subscription level

Get a list of labels (as a JSON array) assigned to a certificate posted on service instance / subscription level. 
If none are found, an empty array is returned. 
Service instance and subaccount are determined by the passed OAuth access token in the Authorization header.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1InstanceCertificatesCertificateNameLabelsGetRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameLabelsGet(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameLabelsGetRequest {
	return ApiV1InstanceCertificatesCertificateNameLabelsGetRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return []Label
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameLabelsGetExecute(r ApiV1InstanceCertificatesCertificateNameLabelsGetRequest) ([]Label, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Label
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesCertificateNameLabelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates/{certificate name}/labels"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v V1SubaccountDestinationsPut400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificateName string
	patchLabels *PatchLabels
}

// A JSON object describing the action performed and an array of labels (as JSON objects) to be assigned to or removed from the certificate. The value of the action property must be either &#x60;ADD&#x60; or &#x60;DELETE&#x60;. Each label JSON object must contain a &#x60;key&#x60; property and a &#x60;values&#x60; property.
func (r ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest) PatchLabels(patchLabels PatchLabels) ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest {
	r.patchLabels = &patchLabels
	return r
}

func (r ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1InstanceCertificatesCertificateNameLabelsPatchExecute(r)
}

/*
V1InstanceCertificatesCertificateNameLabelsPatch Add or remove labels for a certificate posted on service instance / subscription level

Add or remove labels assigned to a certificate posted on service instance / subscription level. 
Service instance and subaccount are determined by the passed OAuth access token in the Authorization header.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameLabelsPatch(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest {
	return ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameLabelsPatchExecute(r ApiV1InstanceCertificatesCertificateNameLabelsPatchRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesCertificateNameLabelsPatch")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates/{certificate name}/labels"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.patchLabels == nil {
		return nil, reportError("patchLabels is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.patchLabels
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v V1SubaccountDestinationsPut400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesCertificateNameLabelsPutRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificateName string
	label *[]Label
}

// An array of labels (as JSON objects) to be assigned to the certificate. Each label JSON object must contain a &#x60;key&#x60; property and a &#x60;values&#x60; property.
func (r ApiV1InstanceCertificatesCertificateNameLabelsPutRequest) Label(label []Label) ApiV1InstanceCertificatesCertificateNameLabelsPutRequest {
	r.label = &label
	return r
}

func (r ApiV1InstanceCertificatesCertificateNameLabelsPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1InstanceCertificatesCertificateNameLabelsPutExecute(r)
}

/*
V1InstanceCertificatesCertificateNameLabelsPut Replace all labels for a certificate posted on service instance / subscription level

Replace all labels assigned to a certificate posted on service instance / subscription level with the labels specified in the request body. 
Service instance and subaccount are determined by the passed OAuth access token in the Authorization header.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name
 @return ApiV1InstanceCertificatesCertificateNameLabelsPutRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameLabelsPut(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNameLabelsPutRequest {
	return ApiV1InstanceCertificatesCertificateNameLabelsPutRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNameLabelsPutExecute(r ApiV1InstanceCertificatesCertificateNameLabelsPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesCertificateNameLabelsPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates/{certificate name}/labels"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.label == nil {
		return nil, reportError("label is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.label
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v V1SubaccountDestinationsPut400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificateName string
	ifNoneMatch *string
	ifMatch *string
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value is different from the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 304 (Not Modified) and empty response body. If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest) IfNoneMatch(ifNoneMatch string) ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value matches the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 412 (Precondition Failed). If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest) IfMatch(ifMatch string) ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest {
	r.ifMatch = &ifMatch
	return r
}

func (r ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest) Execute() ([]PublicKey, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesCertificateNamePublicKeysGetExecute(r)
}

/*
V1InstanceCertificatesCertificateNamePublicKeysGet Get the public part of a specified certificate

Get a certificate chain in PEM format (Base64 encoded string, as a JSON object) of a specified certificate. In case of a keystore, the response will contain certificate chain for each alias. The public part of password-protected keystores can be retrieved only for PEM certificates and certificates generated using attributes. Service instance and subaccount are determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param certificateName Certificate name on instance level
 @return ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNamePublicKeysGet(ctx context.Context, certificateName string) ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest {
	return ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest{
		ApiService: a,
		ctx: ctx,
		certificateName: certificateName,
	}
}

// Execute executes the request
//  @return []PublicKey
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesCertificateNamePublicKeysGetExecute(r ApiV1InstanceCertificatesCertificateNamePublicKeysGetRequest) ([]PublicKey, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []PublicKey
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesCertificateNamePublicKeysGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates/{certificate name}/publicKeys"
	localVarPath = strings.Replace(localVarPath, "{"+"certificate name"+"}", url.PathEscape(parameterValueToString(r.certificateName, "certificateName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ifNoneMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "simple", "")
	}
	if r.ifMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesDeleteRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	filter *string
}

// A filter expression, which specifies what certificates to delete. It can only be an in-list condition.  ## In-list condition  Syntax: &#x60;$filter&#x3D;Name in (&lt;list_of_names&gt;)&#x60;  Deletes all certificates with the specified names from the list. Every name in the list of names should be [percent-encoded](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1) and after that surrounded by single quotes.  For example, let&#39;s look at two certificates with names \&quot;our team&#39;s app.pem\&quot; and \&quot;workflow (new).pem\&quot;.  The query parameter for them would be constructed as follows:  &#x60;&#x60;&#x60; $filter&#x3D;Name in (&#39;our%20team%27s%20app.pem&#39;, &#39;workflow%20%28new%29.pem&#39;) &#x60;&#x60;&#x60;  You can pass this value to curl&#39;s **--data-urlencode** option and the resulting URI for the HTTP request would end like this:  &#x60;&#x60;&#x60; /destination-configuration/v1/subaccountCertificates?$filter&#x3D;Name+in+%28%27our%2520team%2527s%2520app.pem%27%2c+%27workflow%2520%2528new%2529.pem%27%29 &#x60;&#x60;&#x60;  Note: &#x60;Name&#x60; is the only supported field. 
func (r ApiV1InstanceCertificatesDeleteRequest) Filter(filter string) ApiV1InstanceCertificatesDeleteRequest {
	r.filter = &filter
	return r
}

func (r ApiV1InstanceCertificatesDeleteRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesDeleteExecute(r)
}

/*
V1InstanceCertificatesDelete Deletes certificates posted on service instance / subscription level

Deletes certificates posted on service instance / subscription level. Service
instance and subaccount are determined by the passed OAuth access token.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1InstanceCertificatesDeleteRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesDelete(ctx context.Context) ApiV1InstanceCertificatesDeleteRequest {
	return ApiV1InstanceCertificatesDeleteRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return string
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesDeleteExecute(r ApiV1InstanceCertificatesDeleteRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.filter == nil {
		return localVarReturnValue, nil, reportError("filter is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "$filter", r.filter, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesGetRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	filter *string
	includeMetadata *string
	select_ *string
	page *int32
	pageSize *int32
	pageCount *bool
	entityCount *bool
}

// A filter expression, which specifies what certificates to return. It can only be an in-list condition.  Allowed only in the default mode. As such, **$filter** cannot be combined with **$select**, nor **$page**.  ## In-list condition  Syntax: &#x60;$filter&#x3D;Name in (&lt;list_of_names&gt;)&#x60;  Retrieves all certificates with the specified names from the list. Every name in the list of names should be [percent-encoded](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1) and after that surrounded by single quotes.  For example, let&#39;s look at two certificates with names \&quot;our-team&#39;s-app.pem\&quot; and \&quot;SAP_John&#39;s_certificate\&quot;.  The query parameter for them would be constructed as follows:  &#x60;&#x60;&#x60; $filter&#x3D;Name in (&#39;our-team%27s-app.pem&#39;, &#39;SAP_John%27s_certificate&#39;) &#x60;&#x60;&#x60;  You can pass this value to curl&#39;s **--data-urlencode** option and the resulting URI for the HTTP request would end like this:  &#x60;&#x60;&#x60; /destination-configuration/v1/subaccountCertificates?$filter&#x3D;Name+in+%28%27our-team%2527s-app.pem%27%2C+%27SAP_John%2527s_certificate%27%29 &#x60;&#x60;&#x60;  Note: &#x60;Name&#x60; is the only supported field.  ## Has Label condition  Syntax: &#x60;$filter&#x3D;Label[&#39;&lt;label-key&gt;&#39;] HAS (&#39;&lt;label-value-1&gt;&#39;, &#39;&lt;label-value-2&gt;&#39;)&#x60;  Retrieves all certificates that have been assigned labels which contain all of the requested label values.  For example, to get all certificates that have been assigned a label &#39;token-type&#39; with values &#39;xsuaa&#39; and &#39;ias&#39;, the filter would be:  &#x60;&#x60;&#x60; $filter&#x3D;Label[&#39;token-type&#39;] HAS (&#39;xsuaa&#39;, &#39;ias&#39;) &#x60;&#x60;&#x60; 
func (r ApiV1InstanceCertificatesGetRequest) Filter(filter string) ApiV1InstanceCertificatesGetRequest {
	r.filter = &filter
	return r
}

// Include metadata in the response. Each configuration will contain an additional property **$metadata** with the value of an object, containing the names of the requested metadata properties as keys, and their values.  Allowed only in the default mode. As such, **$includeMetadata** cannot be combined with **$select**, nor **$page**.  Syntax: &#x60;&#x60;&#x60; $includeMetadata&#x3D;&lt;metadata1&gt;;&lt;metadata2&gt;;... &#x60;&#x60;&#x60;  Note: Currently only &#x60;modification_time&#x60;, &#x60;etag&#x60;, &#x60;shared_with_subscriber&#x60; and &#x60;labels&#x60; are metadata that can be included. 
func (r ApiV1InstanceCertificatesGetRequest) IncludeMetadata(includeMetadata string) ApiV1InstanceCertificatesGetRequest {
	r.includeMetadata = &includeMetadata
	return r
}

// Enable select mode, in order to retrieve only certificate names.   In select mode the response changes from a list of certificates to a list of their names. Only the &#x60;Name&#x60; field is supported as a value.  Note: Only one mode is allowed for a request. As such, **$select** cannot be combined with **$page**, nor **$filter**. 
func (r ApiV1InstanceCertificatesGetRequest) Select_(select_ string) ApiV1InstanceCertificatesGetRequest {
	r.select_ = &select_
	return r
}

// Enable pagination mode and retrieve the specified page number.  In pagination mode the list of certificates is partitioned into pages of size **$pageSize** and only the specified page is returned. Page numbering starts from 1.  Note: Only one mode is allowed for a request. As such, **$page** cannot be combined with **$select**, nor **$filter**. 
func (r ApiV1InstanceCertificatesGetRequest) Page(page int32) ApiV1InstanceCertificatesGetRequest {
	r.page = &page
	return r
}

// Number of items in each page.  Allowed only in pagination mode (see **$page** query parameter). 
func (r ApiV1InstanceCertificatesGetRequest) PageSize(pageSize int32) ApiV1InstanceCertificatesGetRequest {
	r.pageSize = &pageSize
	return r
}

// Whether to return the information about the total count of pages for the request, via **Page-Count** response header.  Allowed only in pagination mode (see **$page** query parameter). 
func (r ApiV1InstanceCertificatesGetRequest) PageCount(pageCount bool) ApiV1InstanceCertificatesGetRequest {
	r.pageCount = &pageCount
	return r
}

// Whether to return the information about the total count of entities for the request, via **Entity-Count** response header.  Allowed only in pagination mode (see **$page** query parameter). 
func (r ApiV1InstanceCertificatesGetRequest) EntityCount(entityCount bool) ApiV1InstanceCertificatesGetRequest {
	r.entityCount = &entityCount
	return r
}

func (r ApiV1InstanceCertificatesGetRequest) Execute() ([]V1SubaccountCertificatesGet200ResponseInner, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesGetExecute(r)
}

/*
V1InstanceCertificatesGet Get all certificates posted on service instance / subscription level

Get all certificates (as a JSON array) posted on service instance
level. If none is found, an empty list is returned. Service instance and subaccount
are determined by the passed OAuth access token.

For requests which return a large number of certificates, chunked handling of the response will be enabled. If an error occurs with the request processing while chunking is enabled, no response will be returned to the client.

Note: The maximum length of the `<path>?<query>#<fragment>` part of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1InstanceCertificatesGetRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesGet(ctx context.Context) ApiV1InstanceCertificatesGetRequest {
	return ApiV1InstanceCertificatesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []V1SubaccountCertificatesGet200ResponseInner
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesGetExecute(r ApiV1InstanceCertificatesGetRequest) ([]V1SubaccountCertificatesGet200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []V1SubaccountCertificatesGet200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$filter", r.filter, "form", "")
	}
	if r.includeMetadata != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$includeMetadata", r.includeMetadata, "form", "")
	}
	if r.select_ != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$select", r.select_, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$page", r.page, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageSize", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 10
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageSize", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.pageCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageCount", r.pageCount, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "$pageCount", defaultValue, "form", "")
		r.pageCount = &defaultValue
	}
	if r.entityCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$entityCount", r.entityCount, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "$entityCount", defaultValue, "form", "")
		r.entityCount = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesPostRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificate *V1InstanceCertificatesPutRequest
	includeMetadata *string
}

// The certificate (base64 encoded string, as a JSON object) / Certificates (base64 encoded string, as a JSON array) / Certificate attributes / Certificate attributes with CSR (base64 encoded PEM)
func (r ApiV1InstanceCertificatesPostRequest) Certificate(certificate V1InstanceCertificatesPutRequest) ApiV1InstanceCertificatesPostRequest {
	r.certificate = &certificate
	return r
}

// Include metadata in the response.  If configurations were successfully created, the metadata for the newly created configurations is returned.  If the configurations were not created due to conflict (configuration already exists), the metadata for the existing configurations is returned.  In case a single configuration is posted, the response body will be a JSON object with property **$metadata** containing an object with the names of the requested metadata properties as keys, and their values.  In case multiple configurations are posted, each of the results in the bulk operation response will contain an additional property **$metadata** with the value of an object, containing the names of the requested metadata properties as keys, and their values.  Syntax: &#x60;&#x60;&#x60; $includeMetadata&#x3D;&lt;metadata1&gt;;&lt;metadata2&gt;;... &#x60;&#x60;&#x60;  Note: Currently only &#x60;modification_time&#x60;, &#x60;etag&#x60;, and &#x60;shared_with_subscriber&#x60; are metadata that can be included. 
func (r ApiV1InstanceCertificatesPostRequest) IncludeMetadata(includeMetadata string) ApiV1InstanceCertificatesPostRequest {
	r.includeMetadata = &includeMetadata
	return r
}

func (r ApiV1InstanceCertificatesPostRequest) Execute() ([]BulkResponse, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesPostExecute(r)
}

/*
V1InstanceCertificatesPost Post a new certificate or certificates on service instance / subscription level

Post a new certificate (base64 encoded string, as a JSON object) or new certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on service instance / subscription level. Service instance and subaccount are determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1InstanceCertificatesPostRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesPost(ctx context.Context) ApiV1InstanceCertificatesPostRequest {
	return ApiV1InstanceCertificatesPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []BulkResponse
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesPostExecute(r ApiV1InstanceCertificatesPostRequest) ([]BulkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []BulkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.certificate == nil {
		return localVarReturnValue, nil, reportError("certificate is required and must be specified")
	}

	if r.includeMetadata != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$includeMetadata", r.includeMetadata, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.certificate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiV1InstanceCertificatesPutRequest struct {
	ctx context.Context
	ApiService CertificatesOnServiceInstanceSubscriptionLevelAPI
	certificate *V1InstanceCertificatesPutRequest
}

// The certificate (base64 encoded string, as a JSON object) / Certificates (base64 encoded string, as a JSON array) / Certificate attributes / Certificate attributes with CSR (base64 encoded PEM)
func (r ApiV1InstanceCertificatesPutRequest) Certificate(certificate V1InstanceCertificatesPutRequest) ApiV1InstanceCertificatesPutRequest {
	r.certificate = &certificate
	return r
}

func (r ApiV1InstanceCertificatesPutRequest) Execute() (*V1SubaccountDestinationsPut200Response, *http.Response, error) {
	return r.ApiService.V1InstanceCertificatesPutExecute(r)
}

/*
V1InstanceCertificatesPut Update a certificate or certificates on service instance / subscription level

Update a certificate (base64 encoded string, as a JSON object) or certificates (base64 encoded string, as a JSON array) or certificate attributes (certificate is generated by destination service) or certificate attributes with CSR (certificate is generated by destination service via externally provided CSR. The subject DN in the CSR is ignored. Only PEM certificate can be generated.) on service instance / subscription level. Service instance and subaccount is determined by the passed OAuth access token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1InstanceCertificatesPutRequest
*/
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesPut(ctx context.Context) ApiV1InstanceCertificatesPutRequest {
	return ApiV1InstanceCertificatesPutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return V1SubaccountDestinationsPut200Response
func (a *CertificatesOnServiceInstanceSubscriptionLevelAPIService) V1InstanceCertificatesPutExecute(r ApiV1InstanceCertificatesPutRequest) (*V1SubaccountDestinationsPut200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *V1SubaccountDestinationsPut200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CertificatesOnServiceInstanceSubscriptionLevelAPIService.V1InstanceCertificatesPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/instanceCertificates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.certificate == nil {
		return localVarReturnValue, nil, reportError("certificate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.certificate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
