/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type FindADestinationAPI interface {

	/*
	V1DestinationsNameGet Find a destination by name on all levels and return the first match

	Search priority is destination on service instance / subscription level. If none is found, fallbacks to subaccount level (accessible by all apps deployed in the same subaccount).

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param name Destination name
	@return ApiV1DestinationsNameGetRequest
	*/
	V1DestinationsNameGet(ctx context.Context, name string) ApiV1DestinationsNameGetRequest

	// V1DestinationsNameGetExecute executes the request
	//  @return DestinationLookUpResult
	V1DestinationsNameGetExecute(r ApiV1DestinationsNameGetRequest) (*DestinationLookUpResult, *http.Response, error)
}

// FindADestinationAPIService FindADestinationAPI service
type FindADestinationAPIService service

type ApiV1DestinationsNameGetRequest struct {
	ctx context.Context
	ApiService FindADestinationAPI
	name string
	xUserToken *string
	xSubjectToken *string
	xSubjectTokenType *string
	xActorToken *string
	xActorTokenType *string
	xSamlAssertion *string
	xRefreshToken *string
	xCode *string
	xRedirectUri *string
	xCodeVerifier *string
	xTenant *string
	xClientAssertion *string
	xClientAssertionType *string
	xClientAssertionDestinationName *string
	xFragmentName *string
	xFragmentOptional *bool
	xChainName *string
	xChainVarVariableName *string
	includeMetadata *string
	skipCredentials *bool
	skipTokenRetrieval *bool
	ifNoneMatch *string
	ifMatch *string
}

// This header is only taken into account for authentication type that require user information to be provided (such as OAuth2UserTokenExchange, OAuth2JWTBearer, SAPAssertionSSO (deprecated!) and OAuth2SAMLBearerAssertion). If provided, the value must be a user JWT token in encoded form (see https://tools.ietf.org/html/rfc7519). If provided, it will be used with priority over the Authorization header for the token exchange operation. This means that the user token from this header will be used when determining the user and the tenant subdomain and will also be the token, for which token exchange is performed. If this header is not provided, the user token from the Authorization header will be used.
func (r ApiV1DestinationsNameGetRequest) XUserToken(xUserToken string) ApiV1DestinationsNameGetRequest {
	r.xUserToken = &xUserToken
	return r
}

// This header is required and taken into account only for a destination with authentication type OAuth2TokenExchange. It can be used in pair with the &#39;X-subject-token-type&#39; header, specifying the token type. The subject token from this header will be used for the subject_token parameter in the token exchange request (see https://datatracker.ietf.org/doc/html/rfc8693).
func (r ApiV1DestinationsNameGetRequest) XSubjectToken(xSubjectToken string) ApiV1DestinationsNameGetRequest {
	r.xSubjectToken = &xSubjectToken
	return r
}

// This header is required and taken into account only for a destination with authentication type OAuth2TokenExchange. It can be used in pair with the &#39;X-subject-token&#39; header. The value is the format of the subject token as defined by the authorization server. For example, when we use an OAuth 2.0 access token, the value should be &#39;urn:ietf:params:oauth:token-type:access_token&#39;.
func (r ApiV1DestinationsNameGetRequest) XSubjectTokenType(xSubjectTokenType string) ApiV1DestinationsNameGetRequest {
	r.xSubjectTokenType = &xSubjectTokenType
	return r
}

// This header is only taken into account for a destination with authentication type OAuth2TokenExchange. It can be used in pair with the &#39;X-actor-token-type&#39; header, specifying the token type. The actor token from this header will be used for the actor_token parameter in the token exchange request (see https://datatracker.ietf.org/doc/html/rfc8693).
func (r ApiV1DestinationsNameGetRequest) XActorToken(xActorToken string) ApiV1DestinationsNameGetRequest {
	r.xActorToken = &xActorToken
	return r
}

// This header is only taken into account for a destination with authentication type OAuth2TokenExchange. It can be used in pair with the &#39;X-actor-token&#39; header. The value is the format of the actor token as defined by the authorization server. For example, when we use an OAuth 2.0 access token, the value should be &#39;urn:ietf:params:oauth:token-type:access_token&#39;.
func (r ApiV1DestinationsNameGetRequest) XActorTokenType(xActorTokenType string) ApiV1DestinationsNameGetRequest {
	r.xActorTokenType = &xActorTokenType
	return r
}

// If this header is applicable, when executing the token retrieval requests, instead of Destination service internally generating the SAML Assertion and using it as the assertion parameter, the value of this header will be used. This header is only applicable for destinations which have configured authentication type &lt;b&gt;OAuth2SAMLBearerAssertion&lt;/b&gt; and the property &lt;b&gt;SAMLAssertionProvider&lt;/b&gt; with value &lt;b&gt;ClientProvided&lt;/b&gt;. &lt;br/&gt;&lt;br/&gt; If the header is applicable but not provided or contains an empty value, the token retrieval will fail.
func (r ApiV1DestinationsNameGetRequest) XSamlAssertion(xSamlAssertion string) ApiV1DestinationsNameGetRequest {
	r.xSamlAssertion = &xSamlAssertion
	return r
}

// This header is only taken into account for a destination with authentication type OAuth2RefreshToken. This is an additional mandatory parameter that must be provided in the request header. The value must be provided in a refresh token format according to (see https://datatracker.ietf.org/doc/html/rfc6749#section-6) When provided, the refresh token will be used fetch a new refresh and new access token from the configured OAuth2 tokenServiceURL.
func (r ApiV1DestinationsNameGetRequest) XRefreshToken(xRefreshToken string) ApiV1DestinationsNameGetRequest {
	r.xRefreshToken = &xRefreshToken
	return r
}

// This header is only taken into account for a destination with authentication type OAuth2AuthorizationCode. This is a mandatory parameter that must be provided in the request header. The value must be provided in an authorization code format according to (see https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.3) When provided, the authorization code will be exchanged for an access token from the configured OAuth2 tokenServiceURL.
func (r ApiV1DestinationsNameGetRequest) XCode(xCode string) ApiV1DestinationsNameGetRequest {
	r.xCode = &xCode
	return r
}

// This header is only taken into account for a destination with authentication type OAuth2AuthorizationCode. This is an optional parameter, that can be provided in the request header. The value must be provided in a URL-encoded link according to (see https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.3). When a redirect URI was registered in the the configured OAuth2 token service during the authorization code grant, the token service will require the same redirect URI to be provided for that authorization code. If provided, the token service will check if the registered redirect URI matches the requested one. If they do, the authorization code is exchanged for an access token. If not provided in the case of a registered redirect URI, the access token exchange will fail.
func (r ApiV1DestinationsNameGetRequest) XRedirectUri(xRedirectUri string) ApiV1DestinationsNameGetRequest {
	r.xRedirectUri = &xRedirectUri
	return r
}

// This header is only taken into account for a destination with authentication type OAuth2AuthorizationCode. This is an optional parameter, that can be provided in the request header. The value must be provided in a code verifier format according to (see https://datatracker.ietf.org/doc/html/rfc7636#page-8). When an application has generated a code verifier and provided a code challenge derived from it in the authorization code grant, it must send the code verifier for the token exchange. If provided, the configured OAuth2 token service will verify the code challenge and verifier. If they match, the authorization code will be exchanged for an access token. If not provided in the case of a given code challenge in the authorization code grant, the access token exchange will fail.
func (r ApiV1DestinationsNameGetRequest) XCodeVerifier(xCodeVerifier string) ApiV1DestinationsNameGetRequest {
	r.xCodeVerifier = &xCodeVerifier
	return r
}

// This header is taken into account for destinations with authentication type set to OAuth2ClientCredentials or one that requires user information to be provided (such as OAuth2UserTokenExchange, OAuth2JWTBearer, SAPAssertionSSO (deprecated!) and OAuth2SAMLBearerAssertion). It represents the subdomain of the tenant, on behalf of which to fetch an access token, using the configured credentials. The header is required when tokenServiceURLType is Common and the value will be used to replace the tenant placeholder (or will be added as a subdomain if no placeholder is present). If not provided, an error will be returned. If tokenServiceURLType is Dedicated, the use of this header is forbidden and an error will be returned if provided in the request. If both this header and &#39;X-user-token&#39; are provided, the &#39;X-tenant&#39; header will take precedence.
func (r ApiV1DestinationsNameGetRequest) XTenant(xTenant string) ApiV1DestinationsNameGetRequest {
	r.xTenant = &xTenant
	return r
}

// This header is used when OAuth2 Client Assertion Authentication is used. It can be used in pair with the &#39;X-client-assertion-type&#39; header, specifying the assertion type. The value is the assertion that is used to authenticate the client. When using the Client Assertion mechanism, the client secret property in the destination should be empty. Usage of header &#39;X-client-assertion-destination-name&#39; is not allowed if this header is present.
func (r ApiV1DestinationsNameGetRequest) XClientAssertion(xClientAssertion string) ApiV1DestinationsNameGetRequest {
	r.xClientAssertion = &xClientAssertion
	return r
}

// This header provides client assertion type in OAuth2 Client Assertion Authentication flow. It can be used in pair with the &#39;X-client-assertion&#39; header. The value is the format of the Client assertion as defined by the authorization server. For example, when we use JWT token as assertion the value should be &#39;urn:ietf:params:oauth:client-assertion-type:jwt-bearer&#39;. Usage of header &#39;X-client-assertion-destination-name&#39; is not allowed if this header is present.
func (r ApiV1DestinationsNameGetRequest) XClientAssertionType(xClientAssertionType string) ApiV1DestinationsNameGetRequest {
	r.xClientAssertionType = &xClientAssertionType
	return r
}

// This header can be added in order to use client assertion mechanism for the OAuth flows. The value is the name of a destination that makes a client assertion token retrieval. This header can also override the property &#39;clientAssertion.destinationName&#39; of the destination that is a target of this call. Usage of headers &#39;X-client-assertion&#39; and &#39;X-client-assertion-type&#39; is not allowed if this header is present.
func (r ApiV1DestinationsNameGetRequest) XClientAssertionDestinationName(xClientAssertionDestinationName string) ApiV1DestinationsNameGetRequest {
	r.xClientAssertionDestinationName = &xClientAssertionDestinationName
	return r
}

// The names of the &lt;b&gt;destination fragments&lt;/b&gt; used to override and/or extend the requested destination properties. In case of overlapping properties, the values of the fragment properties take priority over the values of the destination properties. The destination fragments must be maintained and available on the same level as the destination. &lt;br/&gt;&lt;br/&gt; In case multiple fragments are required, the fragments must be specified as a comma-separated list, and each fragment will be applied in the order it is listed. &lt;br/&gt;&lt;br/&gt; If all fragments were found and applied to the requested destination, the resulting destination properties will include &lt;b&gt;FragmentName&lt;/b&gt; containing a comma-separated list of all applied fragments.
func (r ApiV1DestinationsNameGetRequest) XFragmentName(xFragmentName string) ApiV1DestinationsNameGetRequest {
	r.xFragmentName = &xFragmentName
	return r
}

// Marks whether the single &lt;b&gt;destination fragment&lt;/b&gt; provided with the &lt;b&gt;X-fragment-name&lt;/b&gt; header is optional. If the fragment is marked as optional and it does not exist, the destination with its original properties will be returned. &lt;br/&gt;&lt;br/&gt; &lt;b&gt;In case multiple fragments are specified, fragment optionality will be disabled. All listed fragments must be maintained and available on the same level as the destination.&lt;/b&gt;
func (r ApiV1DestinationsNameGetRequest) XFragmentOptional(xFragmentOptional bool) ApiV1DestinationsNameGetRequest {
	r.xFragmentOptional = &xFragmentOptional
	return r
}

// This header provides the name of the destination chain, which allows the invocation of multiple Destination service interactions with one request, automatically using the result of one interaction as input for the next one. Currently, only predefined chains are supported. For more information, refer to the [Predefined Destination Chains documentation](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/predefined-destination-chains?version&#x3D;Cloud).
func (r ApiV1DestinationsNameGetRequest) XChainName(xChainName string) ApiV1DestinationsNameGetRequest {
	r.xChainName = &xChainName
	return r
}

// This header provides a property value for a specific destination chain variable. The value of this header will be used to configure the consumption of the chain the request will use. &lt;variable-name&gt; is a placeholder, and must be replaced with the name of a chain-relevant variable. To learn which variables are supported for each chain, refer to the [Predefined Destination Chains documentation](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/predefined-destination-chains?version&#x3D;Cloud) Chain variable headers are only applicable if the &lt;b&gt;X-chain-name&lt;/b&gt; header is provided. Destination chains may use multiple chain variables, in which case each variable value must be provided as a separate chain variable header.
func (r ApiV1DestinationsNameGetRequest) XChainVarVariableName(xChainVarVariableName string) ApiV1DestinationsNameGetRequest {
	r.xChainVarVariableName = &xChainVarVariableName
	return r
}

// Include metadata in the response. The destination returned will contain an additional property **$metadata** with the value of an object, containing the names of the requested metadata properties as keys, and their values.  Syntax: &#x60;&#x60;&#x60; $includeMetadata&#x3D;&lt;metadata1&gt;;&lt;metadata2&gt;;... &#x60;&#x60;&#x60;  Note: Currently only &#x60;labels&#x60; can be included. 
func (r ApiV1DestinationsNameGetRequest) IncludeMetadata(includeMetadata string) ApiV1DestinationsNameGetRequest {
	r.includeMetadata = &includeMetadata
	return r
}

// Credentials are skipped in the returned destination configuration. This parameter is useful especially for OAuth destinations (such as OAuth2UserTokenExchange, OAuth2JWTBearer, OAuth2SAMLBearerAssertion). The client application actually needs the auto-retrieved token by the service, which makes the credentials optional for the application, and in certain cases it is preferred not be returned in the response.
func (r ApiV1DestinationsNameGetRequest) SkipCredentials(skipCredentials bool) ApiV1DestinationsNameGetRequest {
	r.skipCredentials = &skipCredentials
	return r
}

// If set to true, the service will skip the retrieval of the authentication token and the response will contain only the requested destination configuration. If the destination configuration is set to use mTLS for token retrieval and $skipTokenRetrieval&#x3D;true, the response will also contain the content of the token service keystore.
func (r ApiV1DestinationsNameGetRequest) SkipTokenRetrieval(skipTokenRetrieval bool) ApiV1DestinationsNameGetRequest {
	r.skipTokenRetrieval = &skipTokenRetrieval
	return r
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value is different from the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 304 (Not Modified) and empty response body. If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1DestinationsNameGetRequest) IfNoneMatch(ifNoneMatch string) ApiV1DestinationsNameGetRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// This header allows performing an HTTP ETag (entity tag) comparison. If provided, it would let the server determine how the request shall be processed. In case the actual server-side ETag value matches the value passed in this header, the server responds sending the current server-state of the requested resource. Otherwise, the server responds with a status code HTTP 412 (Precondition Failed). If this header is not provided, the server responds with the current server-state of the requested resource.
func (r ApiV1DestinationsNameGetRequest) IfMatch(ifMatch string) ApiV1DestinationsNameGetRequest {
	r.ifMatch = &ifMatch
	return r
}

func (r ApiV1DestinationsNameGetRequest) Execute() (*DestinationLookUpResult, *http.Response, error) {
	return r.ApiService.V1DestinationsNameGetExecute(r)
}

/*
V1DestinationsNameGet Find a destination by name on all levels and return the first match

Search priority is destination on service instance / subscription level. If none is found, fallbacks to subaccount level (accessible by all apps deployed in the same subaccount).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param name Destination name
 @return ApiV1DestinationsNameGetRequest
*/
func (a *FindADestinationAPIService) V1DestinationsNameGet(ctx context.Context, name string) ApiV1DestinationsNameGetRequest {
	return ApiV1DestinationsNameGetRequest{
		ApiService: a,
		ctx: ctx,
		name: name,
	}
}

// Execute executes the request
//  @return DestinationLookUpResult
func (a *FindADestinationAPIService) V1DestinationsNameGetExecute(r ApiV1DestinationsNameGetRequest) (*DestinationLookUpResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DestinationLookUpResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FindADestinationAPIService.V1DestinationsNameGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/destinations/{name}"
	localVarPath = strings.Replace(localVarPath, "{"+"name"+"}", url.PathEscape(parameterValueToString(r.name, "name")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.includeMetadata != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$includeMetadata", r.includeMetadata, "form", "")
	}
	if r.skipCredentials != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$skipCredentials", r.skipCredentials, "form", "")
	}
	if r.skipTokenRetrieval != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "$skipTokenRetrieval", r.skipTokenRetrieval, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xUserToken != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-user-token", r.xUserToken, "simple", "")
	}
	if r.xSubjectToken != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-subject-token", r.xSubjectToken, "simple", "")
	}
	if r.xSubjectTokenType != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-subject-token-type", r.xSubjectTokenType, "simple", "")
	}
	if r.xActorToken != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-actor-token", r.xActorToken, "simple", "")
	}
	if r.xActorTokenType != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-actor-token-type", r.xActorTokenType, "simple", "")
	}
	if r.xSamlAssertion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-samlAssertion", r.xSamlAssertion, "simple", "")
	}
	if r.xRefreshToken != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-refresh-token", r.xRefreshToken, "simple", "")
	}
	if r.xCode != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-code", r.xCode, "simple", "")
	}
	if r.xRedirectUri != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-redirect-uri", r.xRedirectUri, "simple", "")
	}
	if r.xCodeVerifier != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-code-verifier", r.xCodeVerifier, "simple", "")
	}
	if r.xTenant != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-tenant", r.xTenant, "simple", "")
	}
	if r.xClientAssertion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-client-assertion", r.xClientAssertion, "simple", "")
	}
	if r.xClientAssertionType != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-client-assertion-type", r.xClientAssertionType, "simple", "")
	}
	if r.xClientAssertionDestinationName != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-client-assertion-destination-name", r.xClientAssertionDestinationName, "simple", "")
	}
	if r.xFragmentName != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-fragment-name", r.xFragmentName, "simple", "")
	}
	if r.xFragmentOptional != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-fragment-optional", r.xFragmentOptional, "simple", "")
	}
	if r.xChainName != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-chain-name", r.xChainName, "simple", "")
	}
	if r.xChainVarVariableName != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-chain-var-<variable-name>", r.xChainVarVariableName, "simple", "")
	}
	if r.ifNoneMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "simple", "")
	}
	if r.ifMatch != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v JsonErrorMessage
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
