/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1SubaccountDestinationFragmentsGet200ResponseInner - struct for V1SubaccountDestinationFragmentsGet200ResponseInner
type V1SubaccountDestinationFragmentsGet200ResponseInner struct {
	Fragment *Fragment
}

// FragmentAsV1SubaccountDestinationFragmentsGet200ResponseInner is a convenience function that returns Fragment wrapped in V1SubaccountDestinationFragmentsGet200ResponseInner
func FragmentAsV1SubaccountDestinationFragmentsGet200ResponseInner(v *Fragment) V1SubaccountDestinationFragmentsGet200ResponseInner {
	return V1SubaccountDestinationFragmentsGet200ResponseInner{
		Fragment: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1SubaccountDestinationFragmentsGet200ResponseInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Fragment
	err = newStrictDecoder(data).Decode(&dst.Fragment)
	if err == nil {
		jsonFragment, _ := json.Marshal(dst.Fragment)
		if string(jsonFragment) == "{}" { // empty struct
			dst.Fragment = nil
		} else {
			if err = validator.Validate(dst.Fragment); err != nil {
				dst.Fragment = nil
			} else {
				match++
			}
		}
	} else {
		dst.Fragment = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Fragment = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1SubaccountDestinationFragmentsGet200ResponseInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountDestinationFragmentsGet200ResponseInner): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountDestinationFragmentsGet200ResponseInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1SubaccountDestinationFragmentsGet200ResponseInner) MarshalJSON() ([]byte, error) {
	if src.Fragment != nil {
		return json.Marshal(&src.Fragment)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1SubaccountDestinationFragmentsGet200ResponseInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Fragment != nil {
		return obj.Fragment
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1SubaccountDestinationFragmentsGet200ResponseInner) GetActualInstanceValue() (interface{}) {
	if obj.Fragment != nil {
		return *obj.Fragment
	}

	// all schemas are nil
	return nil
}

type NullableV1SubaccountDestinationFragmentsGet200ResponseInner struct {
	value *V1SubaccountDestinationFragmentsGet200ResponseInner
	isSet bool
}

func (v NullableV1SubaccountDestinationFragmentsGet200ResponseInner) Get() *V1SubaccountDestinationFragmentsGet200ResponseInner {
	return v.value
}

func (v *NullableV1SubaccountDestinationFragmentsGet200ResponseInner) Set(val *V1SubaccountDestinationFragmentsGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SubaccountDestinationFragmentsGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SubaccountDestinationFragmentsGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SubaccountDestinationFragmentsGet200ResponseInner(val *V1SubaccountDestinationFragmentsGet200ResponseInner) *NullableV1SubaccountDestinationFragmentsGet200ResponseInner {
	return &NullableV1SubaccountDestinationFragmentsGet200ResponseInner{value: val, isSet: true}
}

func (v NullableV1SubaccountDestinationFragmentsGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SubaccountDestinationFragmentsGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


