/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AttributesAttributesValidity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttributesAttributesValidity{}

// AttributesAttributesValidity Certificate validity
type AttributesAttributesValidity struct {
	// validity time unit
	TimeUnit *string `json:"TimeUnit,omitempty"`
	// value for the validity time unit
	Value *int32 `json:"Value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AttributesAttributesValidity AttributesAttributesValidity

// NewAttributesAttributesValidity instantiates a new AttributesAttributesValidity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributesAttributesValidity() *AttributesAttributesValidity {
	this := AttributesAttributesValidity{}
	return &this
}

// NewAttributesAttributesValidityWithDefaults instantiates a new AttributesAttributesValidity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributesAttributesValidityWithDefaults() *AttributesAttributesValidity {
	this := AttributesAttributesValidity{}
	return &this
}

// GetTimeUnit returns the TimeUnit field value if set, zero value otherwise.
func (o *AttributesAttributesValidity) GetTimeUnit() string {
	if o == nil || IsNil(o.TimeUnit) {
		var ret string
		return ret
	}
	return *o.TimeUnit
}

// GetTimeUnitOk returns a tuple with the TimeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributesValidity) GetTimeUnitOk() (*string, bool) {
	if o == nil || IsNil(o.TimeUnit) {
		return nil, false
	}
	return o.TimeUnit, true
}

// HasTimeUnit returns a boolean if a field has been set.
func (o *AttributesAttributesValidity) HasTimeUnit() bool {
	if o != nil && !IsNil(o.TimeUnit) {
		return true
	}

	return false
}

// SetTimeUnit gets a reference to the given string and assigns it to the TimeUnit field.
func (o *AttributesAttributesValidity) SetTimeUnit(v string) {
	o.TimeUnit = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *AttributesAttributesValidity) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributesValidity) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *AttributesAttributesValidity) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *AttributesAttributesValidity) SetValue(v int32) {
	o.Value = &v
}

func (o AttributesAttributesValidity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttributesAttributesValidity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeUnit) {
		toSerialize["TimeUnit"] = o.TimeUnit
	}
	if !IsNil(o.Value) {
		toSerialize["Value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AttributesAttributesValidity) UnmarshalJSON(data []byte) (err error) {
	varAttributesAttributesValidity := _AttributesAttributesValidity{}

	err = json.Unmarshal(data, &varAttributesAttributesValidity)

	if err != nil {
		return err
	}

	*o = AttributesAttributesValidity(varAttributesAttributesValidity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "TimeUnit")
		delete(additionalProperties, "Value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAttributesAttributesValidity struct {
	value *AttributesAttributesValidity
	isSet bool
}

func (v NullableAttributesAttributesValidity) Get() *AttributesAttributesValidity {
	return v.value
}

func (v *NullableAttributesAttributesValidity) Set(val *AttributesAttributesValidity) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributesAttributesValidity) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributesAttributesValidity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributesAttributesValidity(val *AttributesAttributesValidity) *NullableAttributesAttributesValidity {
	return &NullableAttributesAttributesValidity{value: val, isSet: true}
}

func (v NullableAttributesAttributesValidity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributesAttributesValidity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


