/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1SubaccountCertificatesPutRequest - struct for V1SubaccountCertificatesPutRequest
type V1SubaccountCertificatesPutRequest struct {
	Attributes *Attributes
	Certificate *Certificate
	ArrayOfCertificate *[]Certificate
}

// AttributesAsV1SubaccountCertificatesPutRequest is a convenience function that returns Attributes wrapped in V1SubaccountCertificatesPutRequest
func AttributesAsV1SubaccountCertificatesPutRequest(v *Attributes) V1SubaccountCertificatesPutRequest {
	return V1SubaccountCertificatesPutRequest{
		Attributes: v,
	}
}

// CertificateAsV1SubaccountCertificatesPutRequest is a convenience function that returns Certificate wrapped in V1SubaccountCertificatesPutRequest
func CertificateAsV1SubaccountCertificatesPutRequest(v *Certificate) V1SubaccountCertificatesPutRequest {
	return V1SubaccountCertificatesPutRequest{
		Certificate: v,
	}
}

// []CertificateAsV1SubaccountCertificatesPutRequest is a convenience function that returns []Certificate wrapped in V1SubaccountCertificatesPutRequest
func ArrayOfCertificateAsV1SubaccountCertificatesPutRequest(v *[]Certificate) V1SubaccountCertificatesPutRequest {
	return V1SubaccountCertificatesPutRequest{
		ArrayOfCertificate: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1SubaccountCertificatesPutRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Attributes
	err = newStrictDecoder(data).Decode(&dst.Attributes)
	if err == nil {
		jsonAttributes, _ := json.Marshal(dst.Attributes)
		if string(jsonAttributes) == "{}" { // empty struct
			dst.Attributes = nil
		} else {
			if err = validator.Validate(dst.Attributes); err != nil {
				dst.Attributes = nil
			} else {
				match++
			}
		}
	} else {
		dst.Attributes = nil
	}

	// try to unmarshal data into Certificate
	err = newStrictDecoder(data).Decode(&dst.Certificate)
	if err == nil {
		jsonCertificate, _ := json.Marshal(dst.Certificate)
		if string(jsonCertificate) == "{}" { // empty struct
			dst.Certificate = nil
		} else {
			if err = validator.Validate(dst.Certificate); err != nil {
				dst.Certificate = nil
			} else {
				match++
			}
		}
	} else {
		dst.Certificate = nil
	}

	// try to unmarshal data into ArrayOfCertificate
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCertificate)
	if err == nil {
		jsonArrayOfCertificate, _ := json.Marshal(dst.ArrayOfCertificate)
		if string(jsonArrayOfCertificate) == "{}" { // empty struct
			dst.ArrayOfCertificate = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCertificate); err != nil {
				dst.ArrayOfCertificate = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCertificate = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Attributes = nil
		dst.Certificate = nil
		dst.ArrayOfCertificate = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1SubaccountCertificatesPutRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountCertificatesPutRequest): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountCertificatesPutRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1SubaccountCertificatesPutRequest) MarshalJSON() ([]byte, error) {
	if src.Attributes != nil {
		return json.Marshal(&src.Attributes)
	}

	if src.Certificate != nil {
		return json.Marshal(&src.Certificate)
	}

	if src.ArrayOfCertificate != nil {
		return json.Marshal(&src.ArrayOfCertificate)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1SubaccountCertificatesPutRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Attributes != nil {
		return obj.Attributes
	}

	if obj.Certificate != nil {
		return obj.Certificate
	}

	if obj.ArrayOfCertificate != nil {
		return obj.ArrayOfCertificate
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1SubaccountCertificatesPutRequest) GetActualInstanceValue() (interface{}) {
	if obj.Attributes != nil {
		return *obj.Attributes
	}

	if obj.Certificate != nil {
		return *obj.Certificate
	}

	if obj.ArrayOfCertificate != nil {
		return *obj.ArrayOfCertificate
	}

	// all schemas are nil
	return nil
}

type NullableV1SubaccountCertificatesPutRequest struct {
	value *V1SubaccountCertificatesPutRequest
	isSet bool
}

func (v NullableV1SubaccountCertificatesPutRequest) Get() *V1SubaccountCertificatesPutRequest {
	return v.value
}

func (v *NullableV1SubaccountCertificatesPutRequest) Set(val *V1SubaccountCertificatesPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SubaccountCertificatesPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SubaccountCertificatesPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SubaccountCertificatesPutRequest(val *V1SubaccountCertificatesPutRequest) *NullableV1SubaccountCertificatesPutRequest {
	return &NullableV1SubaccountCertificatesPutRequest{value: val, isSet: true}
}

func (v NullableV1SubaccountCertificatesPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SubaccountCertificatesPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


