/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IdpMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdpMetadata{}

// IdpMetadata struct for IdpMetadata
type IdpMetadata struct {
	// SAML IdP metadata, containing the active X.509 certificate and the passive X.509 certificate (if it exists)
	IdpMetadata *string `json:"idpMetadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdpMetadata IdpMetadata

// NewIdpMetadata instantiates a new IdpMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdpMetadata() *IdpMetadata {
	this := IdpMetadata{}
	return &this
}

// NewIdpMetadataWithDefaults instantiates a new IdpMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdpMetadataWithDefaults() *IdpMetadata {
	this := IdpMetadata{}
	return &this
}

// GetIdpMetadata returns the IdpMetadata field value if set, zero value otherwise.
func (o *IdpMetadata) GetIdpMetadata() string {
	if o == nil || IsNil(o.IdpMetadata) {
		var ret string
		return ret
	}
	return *o.IdpMetadata
}

// GetIdpMetadataOk returns a tuple with the IdpMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdpMetadata) GetIdpMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.IdpMetadata) {
		return nil, false
	}
	return o.IdpMetadata, true
}

// HasIdpMetadata returns a boolean if a field has been set.
func (o *IdpMetadata) HasIdpMetadata() bool {
	if o != nil && !IsNil(o.IdpMetadata) {
		return true
	}

	return false
}

// SetIdpMetadata gets a reference to the given string and assigns it to the IdpMetadata field.
func (o *IdpMetadata) SetIdpMetadata(v string) {
	o.IdpMetadata = &v
}

func (o IdpMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdpMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdpMetadata) {
		toSerialize["idpMetadata"] = o.IdpMetadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdpMetadata) UnmarshalJSON(data []byte) (err error) {
	varIdpMetadata := _IdpMetadata{}

	err = json.Unmarshal(data, &varIdpMetadata)

	if err != nil {
		return err
	}

	*o = IdpMetadata(varIdpMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "idpMetadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdpMetadata struct {
	value *IdpMetadata
	isSet bool
}

func (v NullableIdpMetadata) Get() *IdpMetadata {
	return v.value
}

func (v *NullableIdpMetadata) Set(val *IdpMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableIdpMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableIdpMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdpMetadata(val *IdpMetadata) *NullableIdpMetadata {
	return &NullableIdpMetadata{value: val, isSet: true}
}

func (v NullableIdpMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdpMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


