/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1InstanceDestinationsPutRequest - struct for V1InstanceDestinationsPutRequest
type V1InstanceDestinationsPutRequest struct {
	CreateSubscriptionLevelDestination *CreateSubscriptionLevelDestination
	Destination *Destination
	ArrayOfCreateSubscriptionLevelDestination *[]CreateSubscriptionLevelDestination
	ArrayOfDestination *[]Destination
}

// CreateSubscriptionLevelDestinationAsV1InstanceDestinationsPutRequest is a convenience function that returns CreateSubscriptionLevelDestination wrapped in V1InstanceDestinationsPutRequest
func CreateSubscriptionLevelDestinationAsV1InstanceDestinationsPutRequest(v *CreateSubscriptionLevelDestination) V1InstanceDestinationsPutRequest {
	return V1InstanceDestinationsPutRequest{
		CreateSubscriptionLevelDestination: v,
	}
}

// DestinationAsV1InstanceDestinationsPutRequest is a convenience function that returns Destination wrapped in V1InstanceDestinationsPutRequest
func DestinationAsV1InstanceDestinationsPutRequest(v *Destination) V1InstanceDestinationsPutRequest {
	return V1InstanceDestinationsPutRequest{
		Destination: v,
	}
}

// []CreateSubscriptionLevelDestinationAsV1InstanceDestinationsPutRequest is a convenience function that returns []CreateSubscriptionLevelDestination wrapped in V1InstanceDestinationsPutRequest
func ArrayOfCreateSubscriptionLevelDestinationAsV1InstanceDestinationsPutRequest(v *[]CreateSubscriptionLevelDestination) V1InstanceDestinationsPutRequest {
	return V1InstanceDestinationsPutRequest{
		ArrayOfCreateSubscriptionLevelDestination: v,
	}
}

// []DestinationAsV1InstanceDestinationsPutRequest is a convenience function that returns []Destination wrapped in V1InstanceDestinationsPutRequest
func ArrayOfDestinationAsV1InstanceDestinationsPutRequest(v *[]Destination) V1InstanceDestinationsPutRequest {
	return V1InstanceDestinationsPutRequest{
		ArrayOfDestination: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1InstanceDestinationsPutRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateSubscriptionLevelDestination
	err = newStrictDecoder(data).Decode(&dst.CreateSubscriptionLevelDestination)
	if err == nil {
		jsonCreateSubscriptionLevelDestination, _ := json.Marshal(dst.CreateSubscriptionLevelDestination)
		if string(jsonCreateSubscriptionLevelDestination) == "{}" { // empty struct
			dst.CreateSubscriptionLevelDestination = nil
		} else {
			if err = validator.Validate(dst.CreateSubscriptionLevelDestination); err != nil {
				dst.CreateSubscriptionLevelDestination = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateSubscriptionLevelDestination = nil
	}

	// try to unmarshal data into Destination
	err = newStrictDecoder(data).Decode(&dst.Destination)
	if err == nil {
		jsonDestination, _ := json.Marshal(dst.Destination)
		if string(jsonDestination) == "{}" { // empty struct
			dst.Destination = nil
		} else {
			if err = validator.Validate(dst.Destination); err != nil {
				dst.Destination = nil
			} else {
				match++
			}
		}
	} else {
		dst.Destination = nil
	}

	// try to unmarshal data into ArrayOfCreateSubscriptionLevelDestination
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCreateSubscriptionLevelDestination)
	if err == nil {
		jsonArrayOfCreateSubscriptionLevelDestination, _ := json.Marshal(dst.ArrayOfCreateSubscriptionLevelDestination)
		if string(jsonArrayOfCreateSubscriptionLevelDestination) == "{}" { // empty struct
			dst.ArrayOfCreateSubscriptionLevelDestination = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCreateSubscriptionLevelDestination); err != nil {
				dst.ArrayOfCreateSubscriptionLevelDestination = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCreateSubscriptionLevelDestination = nil
	}

	// try to unmarshal data into ArrayOfDestination
	err = newStrictDecoder(data).Decode(&dst.ArrayOfDestination)
	if err == nil {
		jsonArrayOfDestination, _ := json.Marshal(dst.ArrayOfDestination)
		if string(jsonArrayOfDestination) == "{}" { // empty struct
			dst.ArrayOfDestination = nil
		} else {
			if err = validator.Validate(dst.ArrayOfDestination); err != nil {
				dst.ArrayOfDestination = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfDestination = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateSubscriptionLevelDestination = nil
		dst.Destination = nil
		dst.ArrayOfCreateSubscriptionLevelDestination = nil
		dst.ArrayOfDestination = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1InstanceDestinationsPutRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1InstanceDestinationsPutRequest): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1InstanceDestinationsPutRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1InstanceDestinationsPutRequest) MarshalJSON() ([]byte, error) {
	if src.CreateSubscriptionLevelDestination != nil {
		return json.Marshal(&src.CreateSubscriptionLevelDestination)
	}

	if src.Destination != nil {
		return json.Marshal(&src.Destination)
	}

	if src.ArrayOfCreateSubscriptionLevelDestination != nil {
		return json.Marshal(&src.ArrayOfCreateSubscriptionLevelDestination)
	}

	if src.ArrayOfDestination != nil {
		return json.Marshal(&src.ArrayOfDestination)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1InstanceDestinationsPutRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateSubscriptionLevelDestination != nil {
		return obj.CreateSubscriptionLevelDestination
	}

	if obj.Destination != nil {
		return obj.Destination
	}

	if obj.ArrayOfCreateSubscriptionLevelDestination != nil {
		return obj.ArrayOfCreateSubscriptionLevelDestination
	}

	if obj.ArrayOfDestination != nil {
		return obj.ArrayOfDestination
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1InstanceDestinationsPutRequest) GetActualInstanceValue() (interface{}) {
	if obj.CreateSubscriptionLevelDestination != nil {
		return *obj.CreateSubscriptionLevelDestination
	}

	if obj.Destination != nil {
		return *obj.Destination
	}

	if obj.ArrayOfCreateSubscriptionLevelDestination != nil {
		return *obj.ArrayOfCreateSubscriptionLevelDestination
	}

	if obj.ArrayOfDestination != nil {
		return *obj.ArrayOfDestination
	}

	// all schemas are nil
	return nil
}

type NullableV1InstanceDestinationsPutRequest struct {
	value *V1InstanceDestinationsPutRequest
	isSet bool
}

func (v NullableV1InstanceDestinationsPutRequest) Get() *V1InstanceDestinationsPutRequest {
	return v.value
}

func (v *NullableV1InstanceDestinationsPutRequest) Set(val *V1InstanceDestinationsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstanceDestinationsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstanceDestinationsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstanceDestinationsPutRequest(val *V1InstanceDestinationsPutRequest) *NullableV1InstanceDestinationsPutRequest {
	return &NullableV1InstanceDestinationsPutRequest{value: val, isSet: true}
}

func (v NullableV1InstanceDestinationsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstanceDestinationsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


