/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1InstanceDestinationFragmentsPutRequest - struct for V1InstanceDestinationFragmentsPutRequest
type V1InstanceDestinationFragmentsPutRequest struct {
	CreateSubscriptionLevelFragment *CreateSubscriptionLevelFragment
	Fragment *Fragment
}

// CreateSubscriptionLevelFragmentAsV1InstanceDestinationFragmentsPutRequest is a convenience function that returns CreateSubscriptionLevelFragment wrapped in V1InstanceDestinationFragmentsPutRequest
func CreateSubscriptionLevelFragmentAsV1InstanceDestinationFragmentsPutRequest(v *CreateSubscriptionLevelFragment) V1InstanceDestinationFragmentsPutRequest {
	return V1InstanceDestinationFragmentsPutRequest{
		CreateSubscriptionLevelFragment: v,
	}
}

// FragmentAsV1InstanceDestinationFragmentsPutRequest is a convenience function that returns Fragment wrapped in V1InstanceDestinationFragmentsPutRequest
func FragmentAsV1InstanceDestinationFragmentsPutRequest(v *Fragment) V1InstanceDestinationFragmentsPutRequest {
	return V1InstanceDestinationFragmentsPutRequest{
		Fragment: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1InstanceDestinationFragmentsPutRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateSubscriptionLevelFragment
	err = newStrictDecoder(data).Decode(&dst.CreateSubscriptionLevelFragment)
	if err == nil {
		jsonCreateSubscriptionLevelFragment, _ := json.Marshal(dst.CreateSubscriptionLevelFragment)
		if string(jsonCreateSubscriptionLevelFragment) == "{}" { // empty struct
			dst.CreateSubscriptionLevelFragment = nil
		} else {
			if err = validator.Validate(dst.CreateSubscriptionLevelFragment); err != nil {
				dst.CreateSubscriptionLevelFragment = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateSubscriptionLevelFragment = nil
	}

	// try to unmarshal data into Fragment
	err = newStrictDecoder(data).Decode(&dst.Fragment)
	if err == nil {
		jsonFragment, _ := json.Marshal(dst.Fragment)
		if string(jsonFragment) == "{}" { // empty struct
			dst.Fragment = nil
		} else {
			if err = validator.Validate(dst.Fragment); err != nil {
				dst.Fragment = nil
			} else {
				match++
			}
		}
	} else {
		dst.Fragment = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateSubscriptionLevelFragment = nil
		dst.Fragment = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1InstanceDestinationFragmentsPutRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1InstanceDestinationFragmentsPutRequest): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1InstanceDestinationFragmentsPutRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1InstanceDestinationFragmentsPutRequest) MarshalJSON() ([]byte, error) {
	if src.CreateSubscriptionLevelFragment != nil {
		return json.Marshal(&src.CreateSubscriptionLevelFragment)
	}

	if src.Fragment != nil {
		return json.Marshal(&src.Fragment)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1InstanceDestinationFragmentsPutRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateSubscriptionLevelFragment != nil {
		return obj.CreateSubscriptionLevelFragment
	}

	if obj.Fragment != nil {
		return obj.Fragment
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1InstanceDestinationFragmentsPutRequest) GetActualInstanceValue() (interface{}) {
	if obj.CreateSubscriptionLevelFragment != nil {
		return *obj.CreateSubscriptionLevelFragment
	}

	if obj.Fragment != nil {
		return *obj.Fragment
	}

	// all schemas are nil
	return nil
}

type NullableV1InstanceDestinationFragmentsPutRequest struct {
	value *V1InstanceDestinationFragmentsPutRequest
	isSet bool
}

func (v NullableV1InstanceDestinationFragmentsPutRequest) Get() *V1InstanceDestinationFragmentsPutRequest {
	return v.value
}

func (v *NullableV1InstanceDestinationFragmentsPutRequest) Set(val *V1InstanceDestinationFragmentsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstanceDestinationFragmentsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstanceDestinationFragmentsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstanceDestinationFragmentsPutRequest(val *V1InstanceDestinationFragmentsPutRequest) *NullableV1InstanceDestinationFragmentsPutRequest {
	return &NullableV1InstanceDestinationFragmentsPutRequest{value: val, isSet: true}
}

func (v NullableV1InstanceDestinationFragmentsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstanceDestinationFragmentsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


