/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Fragment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Fragment{}

// Fragment Fragment object
type Fragment struct {
	// Name of the fragment configuration
	FragmentName string `json:"FragmentName"`
	// Name of the fragment property
	PropertyName *string `json:"PropertyName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Fragment Fragment

// NewFragment instantiates a new Fragment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFragment(fragmentName string) *Fragment {
	this := Fragment{}
	this.FragmentName = fragmentName
	return &this
}

// NewFragmentWithDefaults instantiates a new Fragment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFragmentWithDefaults() *Fragment {
	this := Fragment{}
	return &this
}

// GetFragmentName returns the FragmentName field value
func (o *Fragment) GetFragmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FragmentName
}

// GetFragmentNameOk returns a tuple with the FragmentName field value
// and a boolean to check if the value has been set.
func (o *Fragment) GetFragmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FragmentName, true
}

// SetFragmentName sets field value
func (o *Fragment) SetFragmentName(v string) {
	o.FragmentName = v
}

// GetPropertyName returns the PropertyName field value if set, zero value otherwise.
func (o *Fragment) GetPropertyName() string {
	if o == nil || IsNil(o.PropertyName) {
		var ret string
		return ret
	}
	return *o.PropertyName
}

// GetPropertyNameOk returns a tuple with the PropertyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fragment) GetPropertyNameOk() (*string, bool) {
	if o == nil || IsNil(o.PropertyName) {
		return nil, false
	}
	return o.PropertyName, true
}

// HasPropertyName returns a boolean if a field has been set.
func (o *Fragment) HasPropertyName() bool {
	if o != nil && !IsNil(o.PropertyName) {
		return true
	}

	return false
}

// SetPropertyName gets a reference to the given string and assigns it to the PropertyName field.
func (o *Fragment) SetPropertyName(v string) {
	o.PropertyName = &v
}

func (o Fragment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Fragment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["FragmentName"] = o.FragmentName
	if !IsNil(o.PropertyName) {
		toSerialize["PropertyName"] = o.PropertyName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Fragment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"FragmentName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFragment := _Fragment{}

	err = json.Unmarshal(data, &varFragment)

	if err != nil {
		return err
	}

	*o = Fragment(varFragment)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "FragmentName")
		delete(additionalProperties, "PropertyName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFragment struct {
	value *Fragment
	isSet bool
}

func (v NullableFragment) Get() *Fragment {
	return v.value
}

func (v *NullableFragment) Set(val *Fragment) {
	v.value = val
	v.isSet = true
}

func (v NullableFragment) IsSet() bool {
	return v.isSet
}

func (v *NullableFragment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFragment(val *Fragment) *NullableFragment {
	return &NullableFragment{value: val, isSet: true}
}

func (v NullableFragment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFragment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


