/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateSubscriptionLevelFragmentMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubscriptionLevelFragmentMetadata{}

// CreateSubscriptionLevelFragmentMetadata struct for CreateSubscriptionLevelFragmentMetadata
type CreateSubscriptionLevelFragmentMetadata struct {
	// Whether the fragment is shared with the subscriber
	SharedWithSubscriber *bool `json:"shared_with_subscriber,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSubscriptionLevelFragmentMetadata CreateSubscriptionLevelFragmentMetadata

// NewCreateSubscriptionLevelFragmentMetadata instantiates a new CreateSubscriptionLevelFragmentMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubscriptionLevelFragmentMetadata() *CreateSubscriptionLevelFragmentMetadata {
	this := CreateSubscriptionLevelFragmentMetadata{}
	return &this
}

// NewCreateSubscriptionLevelFragmentMetadataWithDefaults instantiates a new CreateSubscriptionLevelFragmentMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubscriptionLevelFragmentMetadataWithDefaults() *CreateSubscriptionLevelFragmentMetadata {
	this := CreateSubscriptionLevelFragmentMetadata{}
	return &this
}

// GetSharedWithSubscriber returns the SharedWithSubscriber field value if set, zero value otherwise.
func (o *CreateSubscriptionLevelFragmentMetadata) GetSharedWithSubscriber() bool {
	if o == nil || IsNil(o.SharedWithSubscriber) {
		var ret bool
		return ret
	}
	return *o.SharedWithSubscriber
}

// GetSharedWithSubscriberOk returns a tuple with the SharedWithSubscriber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubscriptionLevelFragmentMetadata) GetSharedWithSubscriberOk() (*bool, bool) {
	if o == nil || IsNil(o.SharedWithSubscriber) {
		return nil, false
	}
	return o.SharedWithSubscriber, true
}

// HasSharedWithSubscriber returns a boolean if a field has been set.
func (o *CreateSubscriptionLevelFragmentMetadata) HasSharedWithSubscriber() bool {
	if o != nil && !IsNil(o.SharedWithSubscriber) {
		return true
	}

	return false
}

// SetSharedWithSubscriber gets a reference to the given bool and assigns it to the SharedWithSubscriber field.
func (o *CreateSubscriptionLevelFragmentMetadata) SetSharedWithSubscriber(v bool) {
	o.SharedWithSubscriber = &v
}

func (o CreateSubscriptionLevelFragmentMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubscriptionLevelFragmentMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SharedWithSubscriber) {
		toSerialize["shared_with_subscriber"] = o.SharedWithSubscriber
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSubscriptionLevelFragmentMetadata) UnmarshalJSON(data []byte) (err error) {
	varCreateSubscriptionLevelFragmentMetadata := _CreateSubscriptionLevelFragmentMetadata{}

	err = json.Unmarshal(data, &varCreateSubscriptionLevelFragmentMetadata)

	if err != nil {
		return err
	}

	*o = CreateSubscriptionLevelFragmentMetadata(varCreateSubscriptionLevelFragmentMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "shared_with_subscriber")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSubscriptionLevelFragmentMetadata struct {
	value *CreateSubscriptionLevelFragmentMetadata
	isSet bool
}

func (v NullableCreateSubscriptionLevelFragmentMetadata) Get() *CreateSubscriptionLevelFragmentMetadata {
	return v.value
}

func (v *NullableCreateSubscriptionLevelFragmentMetadata) Set(val *CreateSubscriptionLevelFragmentMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubscriptionLevelFragmentMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubscriptionLevelFragmentMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubscriptionLevelFragmentMetadata(val *CreateSubscriptionLevelFragmentMetadata) *NullableCreateSubscriptionLevelFragmentMetadata {
	return &NullableCreateSubscriptionLevelFragmentMetadata{value: val, isSet: true}
}

func (v NullableCreateSubscriptionLevelFragmentMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubscriptionLevelFragmentMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


