/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1SubaccountCertificatesGet200ResponseInner - struct for V1SubaccountCertificatesGet200ResponseInner
type V1SubaccountCertificatesGet200ResponseInner struct {
	Certificate *Certificate
	NameOnly *NameOnly
}

// CertificateAsV1SubaccountCertificatesGet200ResponseInner is a convenience function that returns Certificate wrapped in V1SubaccountCertificatesGet200ResponseInner
func CertificateAsV1SubaccountCertificatesGet200ResponseInner(v *Certificate) V1SubaccountCertificatesGet200ResponseInner {
	return V1SubaccountCertificatesGet200ResponseInner{
		Certificate: v,
	}
}

// NameOnlyAsV1SubaccountCertificatesGet200ResponseInner is a convenience function that returns NameOnly wrapped in V1SubaccountCertificatesGet200ResponseInner
func NameOnlyAsV1SubaccountCertificatesGet200ResponseInner(v *NameOnly) V1SubaccountCertificatesGet200ResponseInner {
	return V1SubaccountCertificatesGet200ResponseInner{
		NameOnly: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1SubaccountCertificatesGet200ResponseInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Certificate
	err = newStrictDecoder(data).Decode(&dst.Certificate)
	if err == nil {
		jsonCertificate, _ := json.Marshal(dst.Certificate)
		if string(jsonCertificate) == "{}" { // empty struct
			dst.Certificate = nil
		} else {
			if err = validator.Validate(dst.Certificate); err != nil {
				dst.Certificate = nil
			} else {
				match++
			}
		}
	} else {
		dst.Certificate = nil
	}

	// try to unmarshal data into NameOnly
	err = newStrictDecoder(data).Decode(&dst.NameOnly)
	if err == nil {
		jsonNameOnly, _ := json.Marshal(dst.NameOnly)
		if string(jsonNameOnly) == "{}" { // empty struct
			dst.NameOnly = nil
		} else {
			if err = validator.Validate(dst.NameOnly); err != nil {
				dst.NameOnly = nil
			} else {
				match++
			}
		}
	} else {
		dst.NameOnly = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Certificate = nil
		dst.NameOnly = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1SubaccountCertificatesGet200ResponseInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountCertificatesGet200ResponseInner): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountCertificatesGet200ResponseInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1SubaccountCertificatesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	if src.Certificate != nil {
		return json.Marshal(&src.Certificate)
	}

	if src.NameOnly != nil {
		return json.Marshal(&src.NameOnly)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1SubaccountCertificatesGet200ResponseInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Certificate != nil {
		return obj.Certificate
	}

	if obj.NameOnly != nil {
		return obj.NameOnly
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1SubaccountCertificatesGet200ResponseInner) GetActualInstanceValue() (interface{}) {
	if obj.Certificate != nil {
		return *obj.Certificate
	}

	if obj.NameOnly != nil {
		return *obj.NameOnly
	}

	// all schemas are nil
	return nil
}

type NullableV1SubaccountCertificatesGet200ResponseInner struct {
	value *V1SubaccountCertificatesGet200ResponseInner
	isSet bool
}

func (v NullableV1SubaccountCertificatesGet200ResponseInner) Get() *V1SubaccountCertificatesGet200ResponseInner {
	return v.value
}

func (v *NullableV1SubaccountCertificatesGet200ResponseInner) Set(val *V1SubaccountCertificatesGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SubaccountCertificatesGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SubaccountCertificatesGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SubaccountCertificatesGet200ResponseInner(val *V1SubaccountCertificatesGet200ResponseInner) *NullableV1SubaccountCertificatesGet200ResponseInner {
	return &NullableV1SubaccountCertificatesGet200ResponseInner{value: val, isSet: true}
}

func (v NullableV1SubaccountCertificatesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SubaccountCertificatesGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


