/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkDeleteSummaryElement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkDeleteSummaryElement{}

// BulkDeleteSummaryElement struct for BulkDeleteSummaryElement
type BulkDeleteSummaryElement struct {
	// The name of the configuration
	Name string `json:"name"`
	// The status of the operation for this configuration
	Status string `json:"status"`
	// This field is only present when the status is \"NOT_FOUND\" and represents the reason for this status
	Reason *string `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkDeleteSummaryElement BulkDeleteSummaryElement

// NewBulkDeleteSummaryElement instantiates a new BulkDeleteSummaryElement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkDeleteSummaryElement(name string, status string) *BulkDeleteSummaryElement {
	this := BulkDeleteSummaryElement{}
	this.Name = name
	this.Status = status
	return &this
}

// NewBulkDeleteSummaryElementWithDefaults instantiates a new BulkDeleteSummaryElement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkDeleteSummaryElementWithDefaults() *BulkDeleteSummaryElement {
	this := BulkDeleteSummaryElement{}
	return &this
}

// GetName returns the Name field value
func (o *BulkDeleteSummaryElement) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BulkDeleteSummaryElement) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BulkDeleteSummaryElement) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *BulkDeleteSummaryElement) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BulkDeleteSummaryElement) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BulkDeleteSummaryElement) SetStatus(v string) {
	o.Status = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BulkDeleteSummaryElement) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeleteSummaryElement) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BulkDeleteSummaryElement) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BulkDeleteSummaryElement) SetReason(v string) {
	o.Reason = &v
}

func (o BulkDeleteSummaryElement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkDeleteSummaryElement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkDeleteSummaryElement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkDeleteSummaryElement := _BulkDeleteSummaryElement{}

	err = json.Unmarshal(data, &varBulkDeleteSummaryElement)

	if err != nil {
		return err
	}

	*o = BulkDeleteSummaryElement(varBulkDeleteSummaryElement)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkDeleteSummaryElement struct {
	value *BulkDeleteSummaryElement
	isSet bool
}

func (v NullableBulkDeleteSummaryElement) Get() *BulkDeleteSummaryElement {
	return v.value
}

func (v *NullableBulkDeleteSummaryElement) Set(val *BulkDeleteSummaryElement) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeleteSummaryElement) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeleteSummaryElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeleteSummaryElement(val *BulkDeleteSummaryElement) *NullableBulkDeleteSummaryElement {
	return &NullableBulkDeleteSummaryElement{value: val, isSet: true}
}

func (v NullableBulkDeleteSummaryElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeleteSummaryElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


