/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1InstanceCertificatesPutRequest - struct for V1InstanceCertificatesPutRequest
type V1InstanceCertificatesPutRequest struct {
	Attributes *Attributes
	Certificate *Certificate
	CreateSubscriptionLevelCertificate *CreateSubscriptionLevelCertificate
	ArrayOfCreateSubscriptionLevelCertificate *[]CreateSubscriptionLevelCertificate
}

// AttributesAsV1InstanceCertificatesPutRequest is a convenience function that returns Attributes wrapped in V1InstanceCertificatesPutRequest
func AttributesAsV1InstanceCertificatesPutRequest(v *Attributes) V1InstanceCertificatesPutRequest {
	return V1InstanceCertificatesPutRequest{
		Attributes: v,
	}
}

// CertificateAsV1InstanceCertificatesPutRequest is a convenience function that returns Certificate wrapped in V1InstanceCertificatesPutRequest
func CertificateAsV1InstanceCertificatesPutRequest(v *Certificate) V1InstanceCertificatesPutRequest {
	return V1InstanceCertificatesPutRequest{
		Certificate: v,
	}
}

// CreateSubscriptionLevelCertificateAsV1InstanceCertificatesPutRequest is a convenience function that returns CreateSubscriptionLevelCertificate wrapped in V1InstanceCertificatesPutRequest
func CreateSubscriptionLevelCertificateAsV1InstanceCertificatesPutRequest(v *CreateSubscriptionLevelCertificate) V1InstanceCertificatesPutRequest {
	return V1InstanceCertificatesPutRequest{
		CreateSubscriptionLevelCertificate: v,
	}
}

// []CreateSubscriptionLevelCertificateAsV1InstanceCertificatesPutRequest is a convenience function that returns []CreateSubscriptionLevelCertificate wrapped in V1InstanceCertificatesPutRequest
func ArrayOfCreateSubscriptionLevelCertificateAsV1InstanceCertificatesPutRequest(v *[]CreateSubscriptionLevelCertificate) V1InstanceCertificatesPutRequest {
	return V1InstanceCertificatesPutRequest{
		ArrayOfCreateSubscriptionLevelCertificate: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1InstanceCertificatesPutRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Attributes
	err = newStrictDecoder(data).Decode(&dst.Attributes)
	if err == nil {
		jsonAttributes, _ := json.Marshal(dst.Attributes)
		if string(jsonAttributes) == "{}" { // empty struct
			dst.Attributes = nil
		} else {
			if err = validator.Validate(dst.Attributes); err != nil {
				dst.Attributes = nil
			} else {
				match++
			}
		}
	} else {
		dst.Attributes = nil
	}

	// try to unmarshal data into Certificate
	err = newStrictDecoder(data).Decode(&dst.Certificate)
	if err == nil {
		jsonCertificate, _ := json.Marshal(dst.Certificate)
		if string(jsonCertificate) == "{}" { // empty struct
			dst.Certificate = nil
		} else {
			if err = validator.Validate(dst.Certificate); err != nil {
				dst.Certificate = nil
			} else {
				match++
			}
		}
	} else {
		dst.Certificate = nil
	}

	// try to unmarshal data into CreateSubscriptionLevelCertificate
	err = newStrictDecoder(data).Decode(&dst.CreateSubscriptionLevelCertificate)
	if err == nil {
		jsonCreateSubscriptionLevelCertificate, _ := json.Marshal(dst.CreateSubscriptionLevelCertificate)
		if string(jsonCreateSubscriptionLevelCertificate) == "{}" { // empty struct
			dst.CreateSubscriptionLevelCertificate = nil
		} else {
			if err = validator.Validate(dst.CreateSubscriptionLevelCertificate); err != nil {
				dst.CreateSubscriptionLevelCertificate = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateSubscriptionLevelCertificate = nil
	}

	// try to unmarshal data into ArrayOfCreateSubscriptionLevelCertificate
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCreateSubscriptionLevelCertificate)
	if err == nil {
		jsonArrayOfCreateSubscriptionLevelCertificate, _ := json.Marshal(dst.ArrayOfCreateSubscriptionLevelCertificate)
		if string(jsonArrayOfCreateSubscriptionLevelCertificate) == "{}" { // empty struct
			dst.ArrayOfCreateSubscriptionLevelCertificate = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCreateSubscriptionLevelCertificate); err != nil {
				dst.ArrayOfCreateSubscriptionLevelCertificate = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCreateSubscriptionLevelCertificate = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Attributes = nil
		dst.Certificate = nil
		dst.CreateSubscriptionLevelCertificate = nil
		dst.ArrayOfCreateSubscriptionLevelCertificate = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1InstanceCertificatesPutRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1InstanceCertificatesPutRequest): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1InstanceCertificatesPutRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1InstanceCertificatesPutRequest) MarshalJSON() ([]byte, error) {
	if src.Attributes != nil {
		return json.Marshal(&src.Attributes)
	}

	if src.Certificate != nil {
		return json.Marshal(&src.Certificate)
	}

	if src.CreateSubscriptionLevelCertificate != nil {
		return json.Marshal(&src.CreateSubscriptionLevelCertificate)
	}

	if src.ArrayOfCreateSubscriptionLevelCertificate != nil {
		return json.Marshal(&src.ArrayOfCreateSubscriptionLevelCertificate)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1InstanceCertificatesPutRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Attributes != nil {
		return obj.Attributes
	}

	if obj.Certificate != nil {
		return obj.Certificate
	}

	if obj.CreateSubscriptionLevelCertificate != nil {
		return obj.CreateSubscriptionLevelCertificate
	}

	if obj.ArrayOfCreateSubscriptionLevelCertificate != nil {
		return obj.ArrayOfCreateSubscriptionLevelCertificate
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1InstanceCertificatesPutRequest) GetActualInstanceValue() (interface{}) {
	if obj.Attributes != nil {
		return *obj.Attributes
	}

	if obj.Certificate != nil {
		return *obj.Certificate
	}

	if obj.CreateSubscriptionLevelCertificate != nil {
		return *obj.CreateSubscriptionLevelCertificate
	}

	if obj.ArrayOfCreateSubscriptionLevelCertificate != nil {
		return *obj.ArrayOfCreateSubscriptionLevelCertificate
	}

	// all schemas are nil
	return nil
}

type NullableV1InstanceCertificatesPutRequest struct {
	value *V1InstanceCertificatesPutRequest
	isSet bool
}

func (v NullableV1InstanceCertificatesPutRequest) Get() *V1InstanceCertificatesPutRequest {
	return v.value
}

func (v *NullableV1InstanceCertificatesPutRequest) Set(val *V1InstanceCertificatesPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstanceCertificatesPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstanceCertificatesPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstanceCertificatesPutRequest(val *V1InstanceCertificatesPutRequest) *NullableV1InstanceCertificatesPutRequest {
	return &NullableV1InstanceCertificatesPutRequest{value: val, isSet: true}
}

func (v NullableV1InstanceCertificatesPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstanceCertificatesPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


