/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V1SubaccountDestinationsPut400Response - struct for V1SubaccountDestinationsPut400Response
type V1SubaccountDestinationsPut400Response struct {
	JsonErrorMessage *JsonErrorMessage
	String *string
}

// JsonErrorMessageAsV1SubaccountDestinationsPut400Response is a convenience function that returns JsonErrorMessage wrapped in V1SubaccountDestinationsPut400Response
func JsonErrorMessageAsV1SubaccountDestinationsPut400Response(v *JsonErrorMessage) V1SubaccountDestinationsPut400Response {
	return V1SubaccountDestinationsPut400Response{
		JsonErrorMessage: v,
	}
}

// stringAsV1SubaccountDestinationsPut400Response is a convenience function that returns string wrapped in V1SubaccountDestinationsPut400Response
func StringAsV1SubaccountDestinationsPut400Response(v *string) V1SubaccountDestinationsPut400Response {
	return V1SubaccountDestinationsPut400Response{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V1SubaccountDestinationsPut400Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into JsonErrorMessage
	err = newStrictDecoder(data).Decode(&dst.JsonErrorMessage)
	if err == nil {
		jsonJsonErrorMessage, _ := json.Marshal(dst.JsonErrorMessage)
		if string(jsonJsonErrorMessage) == "{}" { // empty struct
			dst.JsonErrorMessage = nil
		} else {
			if err = validator.Validate(dst.JsonErrorMessage); err != nil {
				dst.JsonErrorMessage = nil
			} else {
				match++
			}
		}
	} else {
		dst.JsonErrorMessage = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.JsonErrorMessage = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V1SubaccountDestinationsPut400Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountDestinationsPut400Response): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(V1SubaccountDestinationsPut400Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V1SubaccountDestinationsPut400Response) MarshalJSON() ([]byte, error) {
	if src.JsonErrorMessage != nil {
		return json.Marshal(&src.JsonErrorMessage)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V1SubaccountDestinationsPut400Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.JsonErrorMessage != nil {
		return obj.JsonErrorMessage
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V1SubaccountDestinationsPut400Response) GetActualInstanceValue() (interface{}) {
	if obj.JsonErrorMessage != nil {
		return *obj.JsonErrorMessage
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableV1SubaccountDestinationsPut400Response struct {
	value *V1SubaccountDestinationsPut400Response
	isSet bool
}

func (v NullableV1SubaccountDestinationsPut400Response) Get() *V1SubaccountDestinationsPut400Response {
	return v.value
}

func (v *NullableV1SubaccountDestinationsPut400Response) Set(val *V1SubaccountDestinationsPut400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SubaccountDestinationsPut400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SubaccountDestinationsPut400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SubaccountDestinationsPut400Response(val *V1SubaccountDestinationsPut400Response) *NullableV1SubaccountDestinationsPut400Response {
	return &NullableV1SubaccountDestinationsPut400Response{value: val, isSet: true}
}

func (v NullableV1SubaccountDestinationsPut400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SubaccountDestinationsPut400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


