/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateSubscriptionLevelCertificate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubscriptionLevelCertificate{}

// CreateSubscriptionLevelCertificate Certificate/Keystore
type CreateSubscriptionLevelCertificate struct {
	// Name of the certificate/keystore
	Name string `json:"Name"`
	// Type of the object. Could be null if not present
	Type *string `json:"Type,omitempty"`
	// Base64 encoded keystore/certificate binary content
	Content string `json:"Content"`
	Metadata *CreateSubscriptionLevelCertificateMetadata `json:"$metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSubscriptionLevelCertificate CreateSubscriptionLevelCertificate

// NewCreateSubscriptionLevelCertificate instantiates a new CreateSubscriptionLevelCertificate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubscriptionLevelCertificate(name string, content string) *CreateSubscriptionLevelCertificate {
	this := CreateSubscriptionLevelCertificate{}
	this.Name = name
	this.Content = content
	return &this
}

// NewCreateSubscriptionLevelCertificateWithDefaults instantiates a new CreateSubscriptionLevelCertificate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubscriptionLevelCertificateWithDefaults() *CreateSubscriptionLevelCertificate {
	this := CreateSubscriptionLevelCertificate{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSubscriptionLevelCertificate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSubscriptionLevelCertificate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSubscriptionLevelCertificate) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateSubscriptionLevelCertificate) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubscriptionLevelCertificate) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateSubscriptionLevelCertificate) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateSubscriptionLevelCertificate) SetType(v string) {
	o.Type = &v
}

// GetContent returns the Content field value
func (o *CreateSubscriptionLevelCertificate) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateSubscriptionLevelCertificate) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateSubscriptionLevelCertificate) SetContent(v string) {
	o.Content = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateSubscriptionLevelCertificate) GetMetadata() CreateSubscriptionLevelCertificateMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret CreateSubscriptionLevelCertificateMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubscriptionLevelCertificate) GetMetadataOk() (*CreateSubscriptionLevelCertificateMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateSubscriptionLevelCertificate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given CreateSubscriptionLevelCertificateMetadata and assigns it to the Metadata field.
func (o *CreateSubscriptionLevelCertificate) SetMetadata(v CreateSubscriptionLevelCertificateMetadata) {
	o.Metadata = &v
}

func (o CreateSubscriptionLevelCertificate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubscriptionLevelCertificate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Name"] = o.Name
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	toSerialize["Content"] = o.Content
	if !IsNil(o.Metadata) {
		toSerialize["$metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSubscriptionLevelCertificate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Name",
		"Content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubscriptionLevelCertificate := _CreateSubscriptionLevelCertificate{}

	err = json.Unmarshal(data, &varCreateSubscriptionLevelCertificate)

	if err != nil {
		return err
	}

	*o = CreateSubscriptionLevelCertificate(varCreateSubscriptionLevelCertificate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Name")
		delete(additionalProperties, "Type")
		delete(additionalProperties, "Content")
		delete(additionalProperties, "$metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSubscriptionLevelCertificate struct {
	value *CreateSubscriptionLevelCertificate
	isSet bool
}

func (v NullableCreateSubscriptionLevelCertificate) Get() *CreateSubscriptionLevelCertificate {
	return v.value
}

func (v *NullableCreateSubscriptionLevelCertificate) Set(val *CreateSubscriptionLevelCertificate) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubscriptionLevelCertificate) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubscriptionLevelCertificate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubscriptionLevelCertificate(val *CreateSubscriptionLevelCertificate) *NullableCreateSubscriptionLevelCertificate {
	return &NullableCreateSubscriptionLevelCertificate{value: val, isSet: true}
}

func (v NullableCreateSubscriptionLevelCertificate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubscriptionLevelCertificate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


