/*
Destination Service (Cloud Foundry)

Destination Service (Cloud Foundry) REST API provides a way to read and manage destination configurations (including related certificates and fragments) with auto-retrieving and caching of auth tokens.  <br/><br/>Note: For all requests, the maximum length of [a URI](https://tools.ietf.org/html/rfc3986#section-3) is 4000 characters. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AttributesAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttributesAttributes{}

// AttributesAttributes Certificate validity and CN
type AttributesAttributes struct {
	// Certificate common name
	CN *string `json:"CN,omitempty"`
	// Certificate signing request (base64 encoded PEM)
	CSR *string `json:"CSR,omitempty"`
	Validity *AttributesAttributesValidity `json:"Validity,omitempty"`
	// Enable automatic certificate renew when the certificate is close to expiring.
	AutomaticRenew *bool `json:"AutomaticRenew,omitempty"`
	// Password which protects the generated private key (in case of pem) or keystore.
	Password *string `json:"Password,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AttributesAttributes AttributesAttributes

// NewAttributesAttributes instantiates a new AttributesAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributesAttributes() *AttributesAttributes {
	this := AttributesAttributes{}
	var automaticRenew bool = false
	this.AutomaticRenew = &automaticRenew
	return &this
}

// NewAttributesAttributesWithDefaults instantiates a new AttributesAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributesAttributesWithDefaults() *AttributesAttributes {
	this := AttributesAttributes{}
	var automaticRenew bool = false
	this.AutomaticRenew = &automaticRenew
	return &this
}

// GetCN returns the CN field value if set, zero value otherwise.
func (o *AttributesAttributes) GetCN() string {
	if o == nil || IsNil(o.CN) {
		var ret string
		return ret
	}
	return *o.CN
}

// GetCNOk returns a tuple with the CN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributes) GetCNOk() (*string, bool) {
	if o == nil || IsNil(o.CN) {
		return nil, false
	}
	return o.CN, true
}

// HasCN returns a boolean if a field has been set.
func (o *AttributesAttributes) HasCN() bool {
	if o != nil && !IsNil(o.CN) {
		return true
	}

	return false
}

// SetCN gets a reference to the given string and assigns it to the CN field.
func (o *AttributesAttributes) SetCN(v string) {
	o.CN = &v
}

// GetCSR returns the CSR field value if set, zero value otherwise.
func (o *AttributesAttributes) GetCSR() string {
	if o == nil || IsNil(o.CSR) {
		var ret string
		return ret
	}
	return *o.CSR
}

// GetCSROk returns a tuple with the CSR field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributes) GetCSROk() (*string, bool) {
	if o == nil || IsNil(o.CSR) {
		return nil, false
	}
	return o.CSR, true
}

// HasCSR returns a boolean if a field has been set.
func (o *AttributesAttributes) HasCSR() bool {
	if o != nil && !IsNil(o.CSR) {
		return true
	}

	return false
}

// SetCSR gets a reference to the given string and assigns it to the CSR field.
func (o *AttributesAttributes) SetCSR(v string) {
	o.CSR = &v
}

// GetValidity returns the Validity field value if set, zero value otherwise.
func (o *AttributesAttributes) GetValidity() AttributesAttributesValidity {
	if o == nil || IsNil(o.Validity) {
		var ret AttributesAttributesValidity
		return ret
	}
	return *o.Validity
}

// GetValidityOk returns a tuple with the Validity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributes) GetValidityOk() (*AttributesAttributesValidity, bool) {
	if o == nil || IsNil(o.Validity) {
		return nil, false
	}
	return o.Validity, true
}

// HasValidity returns a boolean if a field has been set.
func (o *AttributesAttributes) HasValidity() bool {
	if o != nil && !IsNil(o.Validity) {
		return true
	}

	return false
}

// SetValidity gets a reference to the given AttributesAttributesValidity and assigns it to the Validity field.
func (o *AttributesAttributes) SetValidity(v AttributesAttributesValidity) {
	o.Validity = &v
}

// GetAutomaticRenew returns the AutomaticRenew field value if set, zero value otherwise.
func (o *AttributesAttributes) GetAutomaticRenew() bool {
	if o == nil || IsNil(o.AutomaticRenew) {
		var ret bool
		return ret
	}
	return *o.AutomaticRenew
}

// GetAutomaticRenewOk returns a tuple with the AutomaticRenew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributes) GetAutomaticRenewOk() (*bool, bool) {
	if o == nil || IsNil(o.AutomaticRenew) {
		return nil, false
	}
	return o.AutomaticRenew, true
}

// HasAutomaticRenew returns a boolean if a field has been set.
func (o *AttributesAttributes) HasAutomaticRenew() bool {
	if o != nil && !IsNil(o.AutomaticRenew) {
		return true
	}

	return false
}

// SetAutomaticRenew gets a reference to the given bool and assigns it to the AutomaticRenew field.
func (o *AttributesAttributes) SetAutomaticRenew(v bool) {
	o.AutomaticRenew = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AttributesAttributes) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributesAttributes) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AttributesAttributes) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AttributesAttributes) SetPassword(v string) {
	o.Password = &v
}

func (o AttributesAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttributesAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CN) {
		toSerialize["CN"] = o.CN
	}
	if !IsNil(o.CSR) {
		toSerialize["CSR"] = o.CSR
	}
	if !IsNil(o.Validity) {
		toSerialize["Validity"] = o.Validity
	}
	if !IsNil(o.AutomaticRenew) {
		toSerialize["AutomaticRenew"] = o.AutomaticRenew
	}
	if !IsNil(o.Password) {
		toSerialize["Password"] = o.Password
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AttributesAttributes) UnmarshalJSON(data []byte) (err error) {
	varAttributesAttributes := _AttributesAttributes{}

	err = json.Unmarshal(data, &varAttributesAttributes)

	if err != nil {
		return err
	}

	*o = AttributesAttributes(varAttributesAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "CN")
		delete(additionalProperties, "CSR")
		delete(additionalProperties, "Validity")
		delete(additionalProperties, "AutomaticRenew")
		delete(additionalProperties, "Password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAttributesAttributes struct {
	value *AttributesAttributes
	isSet bool
}

func (v NullableAttributesAttributes) Get() *AttributesAttributes {
	return v.value
}

func (v *NullableAttributesAttributes) Set(val *AttributesAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributesAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributesAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributesAttributes(val *AttributesAttributes) *NullableAttributesAttributes {
	return &NullableAttributesAttributes{value: val, isSet: true}
}

func (v NullableAttributesAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributesAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


