// Code generated by baseimpl generator. DO NOT EDIT.

package v1alpha1

import base "github.com/sap/crossplane-provider-btp/apis/base/security/v1alpha1"

// Re-exported base types for consumer convenience.
type RoleReference = base.RoleReference
type APICredentials = base.APICredentials
