// Code generated by baseimpl generator. DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

	base "github.com/sap/crossplane-provider-btp/apis/base/security/v1alpha1"
)

// RoleCollectionParameters are the configurable fields of a RoleCollection.
type RoleCollectionParameters = base.BaseRoleCollectionParameters

// RoleCollectionObservation are the observable fields of a RoleCollection.
type RoleCollectionObservation = base.BaseRoleCollectionObservation

// XSUAACredentialsReference is a local copy of the base XSUAACredentialsReference struct, with angryjet
// reference markers attached so a ResolveReferences method is generated for the scoped
// resource. JSON tags match the base type exactly so the CRD shape is unchanged.
//
// The Ref field's `reference-{group,kind,apiversion}:` struct tag is inherited verbatim
// from the base type's tag (see Tag below) — the target is identified there. If the
// reference target ever changes, update the base type's tag rather than this template.
type XSUAACredentialsReference struct {
	// xsuaa api credentials used to manage the assignment
	// +kubebuilder:validation:Optional
	APICredentials base.APICredentials `json:"apiCredentials"`
	// +kubebuilder:validation:Optional
	SubaccountApiCredentialSelector *xpv1.Selector `json:"subaccountApiCredentialSelector,omitempty"`
	// +kubebuilder:validation:Optional
	SubaccountApiCredentialRef *xpv1.Reference `json:"subaccountApiCredentialRef,omitempty" reference-group:"security.btp.sap.crossplane.io" reference-kind:"SubaccountApiCredential" reference-apiversion:"v1alpha1"`
	// +crossplane:generate:reference:type=github.com/sap/crossplane-provider-btp/apis/security/v1alpha1.SubaccountApiCredential
	// +crossplane:generate:reference:refFieldName=SubaccountApiCredentialRef
	// +crossplane:generate:reference:selectorFieldName=SubaccountApiCredentialSelector
	// +crossplane:generate:reference:extractor=github.com/sap/crossplane-provider-btp/apis/security/v1alpha1.SubaccountApiCredentialSecret()
	SubaccountApiCredentialSecret string `json:"subaccountApiCredentialSecret,omitempty"`
	// +crossplane:generate:reference:type=github.com/sap/crossplane-provider-btp/apis/security/v1alpha1.SubaccountApiCredential
	// +crossplane:generate:reference:refFieldName=SubaccountApiCredentialRef
	// +crossplane:generate:reference:selectorFieldName=SubaccountApiCredentialSelector
	// +crossplane:generate:reference:extractor=github.com/sap/crossplane-provider-btp/apis/security/v1alpha1.SubaccountApiCredentialSecretNamespace()
	SubaccountApiCredentialSecretNamespace string `json:"subaccountApiCredentialSecretNamespace,omitempty"`
}

// A RoleCollectionSpec defines the desired state of a RoleCollection.
type RoleCollectionSpec struct {
	xpv1.ResourceSpec         `json:",inline"`
	ForProvider               RoleCollectionParameters `json:"forProvider"`
	XSUAACredentialsReference `json:",inline"`
}

// A RoleCollectionStatus represents the observed state of a RoleCollection.
type RoleCollectionStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          RoleCollectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A RoleCollection aggregates roles into a single entity to assign it to users / groups
//
// External-Name Configuration:
//   - Follows Standard: no (uses name as identifier, not a GUID)
//   - Format: Role Collection Name (string)
//   - How to find:
//   - UI: BTP Cockpit → Subaccount → Security → Role Collections → [Role Collection Name]
//   - CLI: btp get security/role-collection `"<name>"` → `name`
//
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,btp}
type RoleCollection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RoleCollectionSpec   `json:"spec"`
	Status RoleCollectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleCollectionList contains a list of RoleCollection
type RoleCollectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleCollection `json:"items"`
}

// RoleCollection type metadata.
var (
	RoleCollectionKind             = reflect.TypeOf(RoleCollection{}).Name()
	RoleCollectionGroupKind        = schema.GroupKind{Group: Group, Kind: RoleCollectionKind}.String()
	RoleCollectionKindAPIVersion   = RoleCollectionKind + "." + SchemeGroupVersion.String()
	RoleCollectionGroupVersionKind = SchemeGroupVersion.WithKind(RoleCollectionKind)
)

func init() {
	SchemeBuilder.Register(&RoleCollection{}, &RoleCollectionList{})
}
