// Code generated by baseimpl generator. DO NOT EDIT.

package v1alpha1

import (
	base "github.com/sap/crossplane-provider-btp/apis/base/security/v1alpha1"
)

// ToBase converts the scoped RoleCollection to a base.BaseRoleCollection.
// This allows the shared logic layer to work with the base type.
func (r *RoleCollection) ToBase() *base.BaseRoleCollection {
	b := &base.BaseRoleCollection{
		ObjectMeta: r.ObjectMeta,
		Spec: base.BaseRoleCollectionSpec{
			ForProvider: r.Spec.ForProvider,
			XSUAACredentialsReference: base.XSUAACredentialsReference{
				APICredentials:                         r.Spec.XSUAACredentialsReference.APICredentials,
				SubaccountApiCredentialSelector:        r.Spec.XSUAACredentialsReference.SubaccountApiCredentialSelector,
				SubaccountApiCredentialRef:             r.Spec.XSUAACredentialsReference.SubaccountApiCredentialRef,
				SubaccountApiCredentialSecret:          r.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecret,
				SubaccountApiCredentialSecretNamespace: r.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecretNamespace,
			},
		},
		Status: base.BaseRoleCollectionStatus{
			AtProvider: r.Status.AtProvider,
		},
	}
	b.Status.Conditions = r.Status.Conditions
	return b
}

// FromBase updates the scoped RoleCollection from a base.BaseRoleCollection.
// This applies changes made by the shared logic layer back to the scoped type.
func (r *RoleCollection) FromBase(b *base.BaseRoleCollection) {
	r.ObjectMeta = b.ObjectMeta
	r.Spec.ForProvider = b.Spec.ForProvider
	r.Spec.XSUAACredentialsReference = XSUAACredentialsReference{
		APICredentials:                         b.Spec.XSUAACredentialsReference.APICredentials,
		SubaccountApiCredentialSelector:        b.Spec.XSUAACredentialsReference.SubaccountApiCredentialSelector,
		SubaccountApiCredentialRef:             b.Spec.XSUAACredentialsReference.SubaccountApiCredentialRef,
		SubaccountApiCredentialSecret:          b.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecret,
		SubaccountApiCredentialSecretNamespace: b.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecretNamespace,
	}
	r.Status.AtProvider = b.Status.AtProvider
	r.Status.Conditions = b.Status.Conditions
}
