// Code generated by baseimpl generator. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

	base "github.com/sap/crossplane-provider-btp/apis/base/security/v1alpha1"
)

// nsRefToRef converts a *xpv1.NamespacedReference into a *xpv1.Reference, dropping the
// Namespace field which the cluster-scoped base type doesn't carry. nil-safe.
func nsRefToRef(in *xpv1.NamespacedReference) *xpv1.Reference {
	if in == nil {
		return nil
	}
	return &xpv1.Reference{Name: in.Name, Policy: in.Policy}
}

// refToNsRef converts a *xpv1.Reference into a *xpv1.NamespacedReference. nil-safe.
// Namespace is left empty since the base type doesn't carry it.
func refToNsRef(in *xpv1.Reference) *xpv1.NamespacedReference {
	if in == nil {
		return nil
	}
	return &xpv1.NamespacedReference{Name: in.Name, Policy: in.Policy}
}

// nsSelToSel converts a *xpv1.NamespacedSelector into a *xpv1.Selector. nil-safe.
func nsSelToSel(in *xpv1.NamespacedSelector) *xpv1.Selector {
	if in == nil {
		return nil
	}
	return &xpv1.Selector{MatchLabels: in.MatchLabels, MatchControllerRef: in.MatchControllerRef, Policy: in.Policy}
}

// selToNsSel converts a *xpv1.Selector into a *xpv1.NamespacedSelector. nil-safe.
func selToNsSel(in *xpv1.Selector) *xpv1.NamespacedSelector {
	if in == nil {
		return nil
	}
	return &xpv1.NamespacedSelector{MatchLabels: in.MatchLabels, MatchControllerRef: in.MatchControllerRef, Policy: in.Policy}
}

// ToBase converts the scoped RoleCollection to a base.BaseRoleCollection.
// This allows the shared logic layer to work with the base type.
func (r *RoleCollection) ToBase() *base.BaseRoleCollection {
	b := &base.BaseRoleCollection{
		ObjectMeta: r.ObjectMeta,
		Spec: base.BaseRoleCollectionSpec{
			ForProvider: r.Spec.ForProvider,
			XSUAACredentialsReference: base.XSUAACredentialsReference{
				APICredentials:                         r.Spec.XSUAACredentialsReference.APICredentials,
				SubaccountApiCredentialSelector:        nsSelToSel(r.Spec.XSUAACredentialsReference.SubaccountApiCredentialSelector),
				SubaccountApiCredentialRef:             nsRefToRef(r.Spec.XSUAACredentialsReference.SubaccountApiCredentialRef),
				SubaccountApiCredentialSecret:          r.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecret,
				SubaccountApiCredentialSecretNamespace: r.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecretNamespace,
			},
		},
		Status: base.BaseRoleCollectionStatus{
			AtProvider: r.Status.AtProvider,
		},
	}
	b.Status.Conditions = r.Status.Conditions
	return b
}

// FromBase updates the scoped RoleCollection from a base.BaseRoleCollection.
// This applies changes made by the shared logic layer back to the scoped type.
func (r *RoleCollection) FromBase(b *base.BaseRoleCollection) {
	r.ObjectMeta = b.ObjectMeta
	r.Spec.ForProvider = b.Spec.ForProvider
	r.Spec.XSUAACredentialsReference = XSUAACredentialsReference{
		APICredentials:                         b.Spec.XSUAACredentialsReference.APICredentials,
		SubaccountApiCredentialSelector:        selToNsSel(b.Spec.XSUAACredentialsReference.SubaccountApiCredentialSelector),
		SubaccountApiCredentialRef:             refToNsRef(b.Spec.XSUAACredentialsReference.SubaccountApiCredentialRef),
		SubaccountApiCredentialSecret:          b.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecret,
		SubaccountApiCredentialSecretNamespace: b.Spec.XSUAACredentialsReference.SubaccountApiCredentialSecretNamespace,
	}
	r.Status.AtProvider = b.Status.AtProvider
	r.Status.Conditions = b.Status.Conditions
}
