// Code generated by baseimpl generator. DO NOT EDIT.

// Package v1alpha1 contains the core resources of the provider.
// +kubebuilder:object:generate=true
// +groupName=security.btp.sap.m.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// Package type metadata.
const (
	Group   = "security.btp.sap.m.crossplane.io"
	Version = "v1alpha1"
)

var (
	// SchemeGroupVersion is group version used to register these objects
	SchemeGroupVersion = schema.GroupVersion{Group: Group, Version: Version}

	// CRDGroupVersion is an alias for SchemeGroupVersion for backwards compatibility.
	CRDGroupVersion = SchemeGroupVersion

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}
)
