//go:build !ignore_autogenerated

/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseDirectoryObservation) DeepCopyInto(out *BaseDirectoryObservation) {
	*out = *in
	if in.Guid != nil {
		in, out := &in.Guid, &out.Guid
		*out = new(string)
		**out = **in
	}
	if in.EntityState != nil {
		in, out := &in.EntityState, &out.EntityState
		*out = new(string)
		**out = **in
	}
	if in.StateMessage != nil {
		in, out := &in.StateMessage, &out.StateMessage
		*out = new(string)
		**out = **in
	}
	if in.Subdomain != nil {
		in, out := &in.Subdomain, &out.Subdomain
		*out = new(string)
		**out = **in
	}
	if in.DirectoryFeatures != nil {
		in, out := &in.DirectoryFeatures, &out.DirectoryFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseDirectoryObservation.
func (in *BaseDirectoryObservation) DeepCopy() *BaseDirectoryObservation {
	if in == nil {
		return nil
	}
	out := new(BaseDirectoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseDirectoryParameters) DeepCopyInto(out *BaseDirectoryParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DirectoryAdmins != nil {
		in, out := &in.DirectoryAdmins, &out.DirectoryAdmins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DirectoryFeatures != nil {
		in, out := &in.DirectoryFeatures, &out.DirectoryFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Subdomain != nil {
		in, out := &in.Subdomain, &out.Subdomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseDirectoryParameters.
func (in *BaseDirectoryParameters) DeepCopy() *BaseDirectoryParameters {
	if in == nil {
		return nil
	}
	out := new(BaseDirectoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseDirectorySpec) DeepCopyInto(out *BaseDirectorySpec) {
	*out = *in
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseDirectorySpec.
func (in *BaseDirectorySpec) DeepCopy() *BaseDirectorySpec {
	if in == nil {
		return nil
	}
	out := new(BaseDirectorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseDirectoryStatus) DeepCopyInto(out *BaseDirectoryStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseDirectoryStatus.
func (in *BaseDirectoryStatus) DeepCopy() *BaseDirectoryStatus {
	if in == nil {
		return nil
	}
	out := new(BaseDirectoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseGlobalAccountObservation) DeepCopyInto(out *BaseGlobalAccountObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseGlobalAccountObservation.
func (in *BaseGlobalAccountObservation) DeepCopy() *BaseGlobalAccountObservation {
	if in == nil {
		return nil
	}
	out := new(BaseGlobalAccountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseGlobalAccountParameters) DeepCopyInto(out *BaseGlobalAccountParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseGlobalAccountParameters.
func (in *BaseGlobalAccountParameters) DeepCopy() *BaseGlobalAccountParameters {
	if in == nil {
		return nil
	}
	out := new(BaseGlobalAccountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseGlobalAccountSpec) DeepCopyInto(out *BaseGlobalAccountSpec) {
	*out = *in
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseGlobalAccountSpec.
func (in *BaseGlobalAccountSpec) DeepCopy() *BaseGlobalAccountSpec {
	if in == nil {
		return nil
	}
	out := new(BaseGlobalAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseGlobalAccountStatus) DeepCopyInto(out *BaseGlobalAccountStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseGlobalAccountStatus.
func (in *BaseGlobalAccountStatus) DeepCopy() *BaseGlobalAccountStatus {
	if in == nil {
		return nil
	}
	out := new(BaseGlobalAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseSubaccountObservation) DeepCopyInto(out *BaseSubaccountObservation) {
	*out = *in
	if in.SubaccountGuid != nil {
		in, out := &in.SubaccountGuid, &out.SubaccountGuid
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.BetaEnabled != nil {
		in, out := &in.BetaEnabled, &out.BetaEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(map[string][]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]string, len(*in))
			for key, val := range *in {
				var outVal []string
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]string, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SubaccountAdmins != nil {
		in, out := &in.SubaccountAdmins, &out.SubaccountAdmins
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Subdomain != nil {
		in, out := &in.Subdomain, &out.Subdomain
		*out = new(string)
		**out = **in
	}
	if in.UsedForProduction != nil {
		in, out := &in.UsedForProduction, &out.UsedForProduction
		*out = new(string)
		**out = **in
	}
	if in.ParentGuid != nil {
		in, out := &in.ParentGuid, &out.ParentGuid
		*out = new(string)
		**out = **in
	}
	if in.GlobalAccountGUID != nil {
		in, out := &in.GlobalAccountGUID, &out.GlobalAccountGUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseSubaccountObservation.
func (in *BaseSubaccountObservation) DeepCopy() *BaseSubaccountObservation {
	if in == nil {
		return nil
	}
	out := new(BaseSubaccountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseSubaccountParameters) DeepCopyInto(out *BaseSubaccountParameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.SubaccountAdmins != nil {
		in, out := &in.SubaccountAdmins, &out.SubaccountAdmins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseSubaccountParameters.
func (in *BaseSubaccountParameters) DeepCopy() *BaseSubaccountParameters {
	if in == nil {
		return nil
	}
	out := new(BaseSubaccountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseSubaccountSpec) DeepCopyInto(out *BaseSubaccountSpec) {
	*out = *in
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseSubaccountSpec.
func (in *BaseSubaccountSpec) DeepCopy() *BaseSubaccountSpec {
	if in == nil {
		return nil
	}
	out := new(BaseSubaccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseSubaccountStatus) DeepCopyInto(out *BaseSubaccountStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseSubaccountStatus.
func (in *BaseSubaccountStatus) DeepCopy() *BaseSubaccountStatus {
	if in == nil {
		return nil
	}
	out := new(BaseSubaccountStatus)
	in.DeepCopyInto(out)
	return out
}
