package main

// Scope constants define the supported Kubernetes resource scopes.
const (
	ScopeCluster    = "cluster"
	ScopeNamespaced = "namespaced"
)

// Marker constants define the code generation markers used in source files.
const (
	MarkerGenerateScoped    = "+codegen:generate:scoped"
	MarkerReferences        = "+codegen:references"
	MarkerReference         = "+codegen:reference:"
	MarkerMethod            = "+codegen:method:"
	MarkerCategories        = "+codegen:categories="
	MarkerDeprecatedVersion = "+codegen:deprecatedversion:warning="
)

// Prefix constants for type name parsing.
const (
	PrefixBase    = "Base"
	PrefixManaged = "Managed"
	SuffixList    = "List"
)

// GeneratedFilePrefix is the filename prefix for all files generated by this tool.
// This distinguishes baseimpl output from other generators (e.g., angryjet uses "zz_generated.").
const GeneratedFilePrefix = "zz_baseimpl_gen."

// NamespacedGroupInfix is inserted before "crossplane.io" to derive the namespaced group name.
// For example: "account.btp.sap.crossplane.io" → "account.btp.sap.m.crossplane.io"
const NamespacedGroupInfix = "m."

// MarkerGroupName is the kubebuilder marker used in doc.go to declare the API group name.
const MarkerGroupName = "+groupName="

// Standard method names that should be skipped during custom method parsing.
var standardMethods = map[string]bool{
	"GetBaseParameters":  true,
	"SetBaseParameters":  true,
	"GetBaseObservation": true,
	"SetBaseObservation": true,
}
