// Code generated by baseimpl generator. DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	xpv2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"

	base "github.com/sap/crossplane-provider-btp/apis/base/account/v1alpha1"
)

// SubaccountParameters are the configurable fields of a Subaccount.
type SubaccountParameters = base.BaseSubaccountParameters

// SubaccountObservation are the observable fields of a Subaccount.
type SubaccountObservation = base.BaseSubaccountObservation

// A SubaccountSpec defines the desired state of a Subaccount.
type SubaccountSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              SubaccountParameters `json:"forProvider"`
}

// A SubaccountStatus represents the observed state of a Subaccount.
type SubaccountStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          SubaccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Subaccount is a managed resource that represents a Subaccount.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,btp}
type Subaccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SubaccountSpec   `json:"spec"`
	Status SubaccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubaccountList contains a list of Subaccount
type SubaccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subaccount `json:"items"`
}

// Subaccount type metadata.
var (
	SubaccountKind             = reflect.TypeOf(Subaccount{}).Name()
	SubaccountGroupKind        = schema.GroupKind{Group: Group, Kind: SubaccountKind}.String()
	SubaccountKindAPIVersion   = SubaccountKind + "." + SchemeGroupVersion.String()
	SubaccountGroupVersionKind = SchemeGroupVersion.WithKind(SubaccountKind)
)

func init() {
	SchemeBuilder.Register(&Subaccount{}, &SubaccountList{})
}
