# Example configuration showing the refined filtering logic

resources:
  # Subaccount with only displayName (primary identifier) - other fields are optional
  - subaccount:
      displayName: "MySubaccount.*"
      managementPolicies: [Observe]
  
  # Subaccount with displayName and additional optional criteria
  - subaccount:
      displayName: "ProductionSubaccount.*"
      region: "us-east-1"
      description: "Production.*"
      managementPolicies: [Observe]
  
  # Directory with only displayName (primary identifier) - other fields are optional
  - directory:
      displayName: "MyDirectory.*"
      managementPolicies: [Observe]
  
  # Directory with displayName and additional optional criteria
  - directory:
      displayName: "ProductionDirectory.*"
      description: "Production.*"
      directoryFeatures: ".*"
      managementPolicies: [Observe]
  
  # Entitlement filtering remains unchanged - all three fields are still required
  - entitlement:
      serviceName: ".*"
      servicePlanName: ".*"
      subaccountGuid: ".*"
      managementPolicies: [Observe]

providerConfigRef:
  name: default