# Configuration for xpbtp CLI live test
# Targets the mirza-subaccount in the test BTP environment

resources:
  # Primary test subaccount - mirza-subaccount
  - subaccount:
      displayName: "mirza-subaccount"
      managementPolicies: [Observe]
      subaccountAdmins: ["dummy@example.com"]

providerConfigRef:
  name: default-canary