// Code generated by baseimpl generator. DO NOT EDIT.

package subaccount

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/pkg/errors"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	apisv1alpha1 "github.com/sap/crossplane-provider-btp/apis/namespaced/account/v1alpha1"
	logic "github.com/sap/crossplane-provider-btp/internal/controller/logic/account/subaccount"
)

const (
	errNotSubaccount = "managed resource is not a Subaccount custom resource"
)

// Options is the per-Setup configuration; re-exported from the logic package so the
// per-group setup file can alias it without importing logic directly.
type Options = logic.Options

// Setup adds a controller that reconciles Subaccount managed resources.
func Setup(mgr ctrl.Manager, o Options) error {
	return logic.Setup(mgr, o,
		&apisv1alpha1.Subaccount{},
		apisv1alpha1.SubaccountGroupKind,
		apisv1alpha1.SubaccountGroupVersionKind,
		makeExternal,
	)
}

func makeExternal(ctx context.Context, mg resource.Managed, kube client.Client) (managed.ExternalClient, error) {
	cr, ok := mg.(*apisv1alpha1.Subaccount)
	if !ok {
		return nil, errors.New(errNotSubaccount)
	}
	_ = cr

	svc, err := logic.Connect(ctx, mg, kube)
	if err != nil {
		return nil, err
	}

	return &external{
		kube:   kube,
		client: svc,
	}, nil
}

type external struct {
	kube   client.Client
	client logic.Client
}

func (c *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*apisv1alpha1.Subaccount)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errNotSubaccount)
	}

	baseCR := cr.ToBase()

	if err := logic.MigrateExternalName(c.client, ctx, mg, baseCR, c.kube); err != nil {
		return managed.ExternalObservation{}, err
	}

	obs, err := logic.Observe(c.client, ctx, mg, baseCR)
	if err != nil {
		return obs, err
	}

	cr.FromBase(baseCR)

	return obs, nil
}

func (c *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*apisv1alpha1.Subaccount)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errNotSubaccount)
	}

	baseCR := cr.ToBase()

	result, err := logic.Create(c.client, ctx, mg, baseCR)
	if err != nil {
		return result, err
	}

	cr.FromBase(baseCR)
	cr.SetAnnotations(baseCR.GetAnnotations())

	return result, nil
}

func (c *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*apisv1alpha1.Subaccount)
	if !ok {
		return managed.ExternalUpdate{}, errors.New(errNotSubaccount)
	}

	baseCR := cr.ToBase()

	result, err := logic.Update(c.client, ctx, mg, baseCR)
	if err != nil {
		return result, err
	}

	cr.FromBase(baseCR)

	return result, nil
}

func (c *external) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*apisv1alpha1.Subaccount)
	if !ok {
		return managed.ExternalDelete{}, errors.New(errNotSubaccount)
	}

	baseCR := cr.ToBase()

	result, err := logic.Delete(c.client, ctx, mg, baseCR)
	if err != nil {
		return result, err
	}

	cr.FromBase(baseCR)

	return result, nil
}

func (c *external) Disconnect(ctx context.Context) error {
	return nil
}
