apiVersion: oidc.btp.sap.crossplane.io/v1alpha1
kind: CertBasedOIDCLogin
metadata:
  name: example-login
spec:
  forProvider:
    issuer: <ISSUER_URL>
    clientId: <CLIENT_ID>
    certificate:
      type: sap-ias
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: example-login-cert-secret
        key: cert
    password:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: example-login-cert-secret
        key: password
  writeConnectionSecretToRef:
    name: oidc-token
    namespace: crossplane-system
---
# To generate cert secret from downloaded cert:
# kubectl create secret generic example-login-cert-secret --namespace=crossplane-system --from-file=cert=/tmp/personal.p12
---
