apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: Subaccount
metadata:
  namespace: default
  name: entitlement-sa-test
spec:
  providerConfigRef:
    name: account-provider-config
  forProvider:
    displayName: e2e-test-sa-entx
    region: eu10
    subdomain: e2e-test-sa-entx
    labels:
      safe-to-delete: [ "yes" ]
    subaccountAdmins:
      - <EMAIL>
