//go:build !ignore_autogenerated

/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseRoleCollectionObservation) DeepCopyInto(out *BaseRoleCollectionObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.RoleReferences != nil {
		in, out := &in.RoleReferences, &out.RoleReferences
		*out = new([]RoleReference)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RoleReference, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseRoleCollectionObservation.
func (in *BaseRoleCollectionObservation) DeepCopy() *BaseRoleCollectionObservation {
	if in == nil {
		return nil
	}
	out := new(BaseRoleCollectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseRoleCollectionParameters) DeepCopyInto(out *BaseRoleCollectionParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.RoleReferences != nil {
		in, out := &in.RoleReferences, &out.RoleReferences
		*out = make([]RoleReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseRoleCollectionParameters.
func (in *BaseRoleCollectionParameters) DeepCopy() *BaseRoleCollectionParameters {
	if in == nil {
		return nil
	}
	out := new(BaseRoleCollectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseRoleCollectionSpec) DeepCopyInto(out *BaseRoleCollectionSpec) {
	*out = *in
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseRoleCollectionSpec.
func (in *BaseRoleCollectionSpec) DeepCopy() *BaseRoleCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(BaseRoleCollectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseRoleCollectionStatus) DeepCopyInto(out *BaseRoleCollectionStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseRoleCollectionStatus.
func (in *BaseRoleCollectionStatus) DeepCopy() *BaseRoleCollectionStatus {
	if in == nil {
		return nil
	}
	out := new(BaseRoleCollectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleReference) DeepCopyInto(out *RoleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleReference.
func (in *RoleReference) DeepCopy() *RoleReference {
	if in == nil {
		return nil
	}
	out := new(RoleReference)
	in.DeepCopyInto(out)
	return out
}
