// Code generated by baseimpl generator. DO NOT EDIT.

package v1alpha1

import base "github.com/sap/crossplane-provider-btp/apis/base/account/v1alpha1"

// Re-exported base variables and constants for consumer convenience.
const SubaccountOperatorLabel = base.SubaccountOperatorLabel

var DirectoryEntityStateOk = base.DirectoryEntityStateOk
