//go:build e2e

// Code initially generated by test-generator.

package e2e

import (
	"context"
	"testing"
	"time"

	"github.com/crossplane-contrib/xp-testing/pkg/envvar"
	"github.com/crossplane-contrib/xp-testing/pkg/resources"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	meta_api "github.com/sap/crossplane-provider-btp/apis"
	"github.com/sap/crossplane-provider-btp/apis/security/v1alpha1"
	res "sigs.k8s.io/e2e-framework/klient/k8s/resources"
	"sigs.k8s.io/e2e-framework/klient/wait"
	"sigs.k8s.io/e2e-framework/pkg/envconf"
	"sigs.k8s.io/e2e-framework/pkg/features"
)

const (
	IDP_URL_ENV_KEY = "IDP_URL"
)

func Test_SubaccountTrustConfiguration_v1alpha1(t *testing.T) {
	resource := resources.ResourceTestConfig{
		Kind:              "SubaccountTrustConfiguration",
		ResourceDirectory: "testdata/crs/SubaccountTrustConfiguration",
	}

	fB := features.New(resource.Kind)
	fB.WithLabel("kind", resource.Kind)
	fB.Setup(
		func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			// as soon as we move to use the xp-testing framework, we can remove this manually setup and use the preconfigured one
			r, _ := res.New(cfg.Client().RESTConfig())
			_ = meta_api.AddToScheme(r.GetScheme())

			t.Logf("Apply %s", resource.Kind)
			resources.ImportResources(ctx, t, cfg, resource.ResourceDirectory)

			return ctx
		},
	)
	fB.Assess("create", resource.AssessCreate)
	fB.Assess("delete", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
		trustConfig := &v1alpha1.SubaccountTrustConfiguration{}
		MustGetResource(t, cfg, "e2e-trustconfiguration", nil, trustConfig)
		resources.AwaitResourceDeletionOrFail(ctx, t, cfg, trustConfig)

		return DeleteResourcesIgnoreMissing(ctx, t, cfg, resource.Kind, wait.WithTimeout(time.Minute*5))
	})
	fB.Teardown(resource.Teardown)

	testenv.Test(t, fB.Feature())
}

// TestSubaccountTrustConfigurationImportFlow tests the import flow for SubaccountTrustConfiguration
// according to the External Name Handling ADR.
//
// SubaccountTrustConfiguration is an ADR exception: the external-name is the trust configuration's
// origin key (e.g. "sap.custom"), not a GUID. Import IS supported because the origin key can be
// retrieved from the BTP API and used to re-adopt an existing trust configuration.
func TestSubaccountTrustConfigurationImportFlow(t *testing.T) {
	const importK8sResName = "trust-config-import-test"

	idpURL := envvar.GetOrPanic(IDP_URL_ENV_KEY)

	importTester := NewImportTester(
		&v1alpha1.SubaccountTrustConfiguration{
			Spec: v1alpha1.SubaccountTrustConfigurationSpec{
				ForProvider: v1alpha1.SubaccountTrustConfigurationParameters{
					IdentityProvider: &idpURL,
					SubaccountRef: &xpv1.Reference{
						Name: "sub-trust-import-test",
					},
				},
			},
		},
		importK8sResName,
		WithWaitCreateTimeout[*v1alpha1.SubaccountTrustConfiguration](wait.WithTimeout(5*time.Minute)),
		WithWaitDeletionTimeout[*v1alpha1.SubaccountTrustConfiguration](wait.WithTimeout(3*time.Minute)),
		WithDependentResourceDirectory[*v1alpha1.SubaccountTrustConfiguration]("./testdata/crs/SubaccountTrustConfiguration/import"),
		WithWaitDependentResourceTimeout[*v1alpha1.SubaccountTrustConfiguration](wait.WithTimeout(15*time.Minute)),
	)

	testenv.Test(
		t,
		importTester.BuildTestFeature("SubaccountTrustConfiguration Import Flow").Feature(),
	)
}
