# This workflow is triggered by the user and runs the REUSE compliance check (reuse lint) on the repository.

name: REUSE Compliance Check
permissions:
  contents: read

on: 
  workflow_call:
      

jobs:
  lint-reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0