# This workflow will run make reviewable and make check-diff as checks

name: Reviewable&Check-Diff
permissions:
  contents: read

on:
  workflow_call: 

jobs:
  reviewable-checkdiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Install Go tools
      run: go install tool

    - name: Make Reviewable
      run: make reviewable
      env:
        RUNNING_IN_CI: 'true'
    - name: Make Check-Diff
      run: make check-diff
