name: Check for Personal Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-pii-check:
    uses: ./.github/workflows/check-personal-data.lib.yaml
    permissions:
      contents: read
